Advanced Guides > Compotion API > Introduction の翻訳
vuejs-jp/ja.vuejs.org pull request #101
Opened 2020-10-06 09:06 UTC by saitoeku3

resolve #32 

## Description of Problem

https://v3.vuejs.org/guide/composition-api-introduction.html の翻訳を行ったのでレビューをお願いします。

## Additional Information

作業に時間がかかったためご迷惑をおかけしてしまい、申し訳ありません。
いくつか悩んだ箇所があるので共有させていただきます。

- `a presumedly external API`:  「おそらく外部 API」や「外部 API のようなもの」は違和感があったため「適当な外部 API」にしました。
- `the drill` (L482): 「ドリル」は違和感があったため「ノウハウ」にしました。

2020-10-06 15:19 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
翻訳内容はほぼ大丈夫です。
細かい部分コメントしていますが、対応よろしくお願いします！

2020-10-06 15:19 UTC, kazupon commented on src/guide/composition-api-introduction.md
> +このような分離は、複雑なコンポーネントを理解ししてメンテナンスすることを難しくします。このオプションの分離は背景にある論理的な関心事をわかりづらくします。さらに、単一の論理的な関心事に取り組む場合、関連するコードのオプションブロックを何度も "ジャンプ" する必要があります。
typo の修正お願いします。 🙏 
```suggestion
このような分離は、複雑なコンポーネントを理解してメンテナンスすることを難しくします。このオプションの分離は背景にある論理的な関心事をわかりづらくします。さらに、単一の論理的な関心事に取り組む場合、関連するコードのオプションブロックを何度も "ジャンプ" する必要があります。
```

2020-10-06 15:19 UTC, kazupon commented on src/guide/composition-api-introduction.md
> +`setup` をコンポーネントに追加しましょう:
正しい訳ですが、文章の流れが自然になるように、以下でお願いします！ 🙏 
```suggestion
`setup` をコンポーネントに追加してみましょう:
```

2020-10-06 15:19 UTC, kazupon commented on src/guide/composition-api-introduction.md
> +    return {} // ここで返されるものは残りの要素で使用可能です
`the rest of the component` の訳ですが、"rest` はコンポーネントオプションのことを示しているので、以下のような訳でどうでしょうか。
こちらの方が分かりやすいかと思います。他にいい訳があれば、お願いします！

```suggestion
    return {} // ここで返されるものはコンポーネントで他のオプションで使用可能です
```

2020-10-06 15:19 UTC, kazupon commented on src/guide/composition-api-introduction.md
> +  // 残りの要素
少し原文自体がよくない感じなのですが、ここのコメントはコンポーネントの他のオプションのこと示しているので、以下の訳でどうでしょうか。
```suggestion
  // 以降、コンポーネントの"他"のオプション
```

2020-10-06 15:19 UTC, kazupon commented on src/guide/composition-api-introduction.md
> +それを `setup` 関数に追加しましょう:
前の文章の流れから、以下のように意訳気味ではどうでしょう。
```suggestion
では、`setup` 関数にそれを追加してみましょう:
```

2020-10-06 15:48 UTC, potato4d reviewed
Pull Request ありがとうございます！

いくつか nits をコメントしました 📝 
主に読みやすさの観点です。

2020-10-06 15:48 UTC, potato4d commented on src/guide/composition-api-introduction.md
> +**その仕組をざっと見てみましょう。**
```suggestion
**その仕組みをざっと見てみましょう。**
```

[nits] こちらのほうがより一般的かもしれません。

2020-10-06 15:48 UTC, potato4d commented on src/guide/composition-api-introduction.md
> +コンポーネント内の `user` プロパティに `watch` オプションを使用してウォッチャを追加するのと同じように、Vue からインポートした `watch` 関数を使用することができます。それは 3 つの引数を受け付けます:
```suggestion
コンポーネント内の `user` プロパティに `watch` オプションを使用してウォッチャを追加するのと同じように、Vue からインポートした `watch` 関数を使用することができます。それは以下の 3 つの引数を受け付けます:
```

日本語訳の読みやすさの面で、 `以下の` をつけると良いかもしれません

2020-10-06 15:50 UTC, potato4d commented on src/guide/composition-api-introduction.md
> +他の**論理的な関心事**にも同じことができますが、既に疑問があるかもしれません。- _これはコードを `setup` オプションに移動させて肥大させるだけではありませんか？_ そのため他の責務に移る前に、まず上記のコードをスタンドアローンな**コンポジション関数**に抽出します。 `useUserRepositories` の作成から始めましょう:
```suggestion
他の**論理的な関心事**にも同じことができますが、既に疑問があるかもしれません。- _これはコードを `setup` オプションに移動させて肥大させるだけではありませんか？_ そのため他の責務に移る前に、まず上記のコードをスタンドアロンな**コンポジション関数**に抽出します。 `useUserRepositories` の作成から始めましょう:
```

すみません！ここだけ `スタンドアロン` でお願いします。
このページ内で `スタンドアローン` と `スタンドアロン` が両方あったのですが、基本的な長音の取り扱いと、 v2 ドキュメントの歴史的に `スタンドアロン` で統一したいと思います。

https://github.com/vuejs/jp.vuejs.org/commit/5c56077ff52e294915e476319c47e3dc4e08f0d0

2020-10-07 03:00 UTC, saitoeku3 commented on src/guide/composition-api-introduction.md
> +    return {} // ここで返されるものは残りの要素で使用可能です
「ここで返されるものはコンポーネント "の" 他のオプションで使用可能です」のほうが日本語として自然な気がしました！

2020-10-07 03:03 UTC, saitoeku3 commented on src/guide/composition-api-introduction.md
> +他の**論理的な関心事**にも同じことができますが、既に疑問があるかもしれません。- _これはコードを `setup` オプションに移動させて肥大させるだけではありませんか？_ そのため他の責務に移る前に、まず上記のコードをスタンドアローンな**コンポジション関数**に抽出します。 `useUserRepositories` の作成から始めましょう:
ミスでした…！指摘ありがとうございます 🙏

2020-10-07 03:05 UTC, saitoeku3 commented
@kazupon @potato4d 修正完了しました！レビューありがとうございます。

2020-10-08 03:14 UTC, kazupon commented on src/guide/composition-api-introduction.md
> +    return {} // ここで返されるものは残りの要素で使用可能です
そうですね。それでいきましょう！

2020-10-08 03:15 UTC, kazupon approved these changes

2020-10-08 03:16 UTC, kazupon commented
対応ありがとうございました！
マージしますね！

翻訳ありがとうございました！

2020-10-08 03:16 UTC, merged