Transitions & Animation > Enter & Leave Transitions  の翻訳
vuejs-jp/ja.vuejs.org pull request #102
Opened 2020-10-08 14:26 UTC by potato4d

resolve #22 

Enter & Leave Transitions  のセクションを翻訳しました。

2020-10-08 14:31 UTC, potato4d reviewed
翻訳メモを追加 📝 

@kazupon 
全体的に v2 のドキュメントのままの部分が多かったので、その部分はそのまま持ってきて必要な部分について +α の翻訳を入れている形です。

最後のデモの部分がかなり自信ないのでコメントもらえると助かります 🙏

2020-10-08 14:31 UTC, potato4d commented on package.json
> +    "lint:single": "textlint --rulesdir ./node_modules/textlint-checker-for-vuejs-jp-docs/rules/textlint-rule-vue-jp-docs -f pretty-error"
[nits]
単体のファイルの Lint がなかったので追加 (既に取り込まれているファイルで Lint 落ちが 27 件あるので、修正と Lint の CI 追加を急ぎます)

2020-10-08 14:31 UTC, potato4d commented on src/guide/transitions-enterleave.md
> -There are six classes applied for enter/leave transitions.
[note]
v2 ではこれらであり直訳としては正しいが、読みやすさの面で以下へと変更しました。

https://jp.vuejs.org/v2/guide/transitions.html#%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B8%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%AF%E3%83%A9%E3%82%B9

2020-10-08 14:31 UTC, potato4d commented on src/guide/transitions-enterleave.md
> +ただ、そうするわけにはいかない場合や、より複雑な in と out の動きの扱いについてコーディネートする必要がある場合に、Vue は非常に便利な **トランジションモード** というユーティリティを提供しています。
[note]
ここ、はじめは coordinated を調整として翻訳していましたが、後述の部分で coordinated をカタカナ語として使うほうが適切な場面が出てきたので統一しました。

2020-10-08 14:31 UTC, potato4d commented on src/guide/transitions-enterleave.md
> +これを利用することによって、以下のようなより表現力のある動きをコーディネートすることができます。二つの要素がお互いの間でトランジションしていますが、そのお互いの大きさが同じであり、水平方向の 0 の位置で重なるため、一つの要素の動きの流れに見えます。このような細かな調整は、よりリアルなマイクロインタラクションの表現で役立ちます:
デモ見ながら翻訳したんですが、2つの要素が横向きになるタイミングで重なり、その結果一つの要素として見えるということを言いたい内容ではあるのですが、直訳すると理解できない文章になりそうなのでこうしました 📝 
coordinated をコーディネートのカタカナ語にしたのはここ由来です。

2020-10-08 14:31 UTC, potato4d commented on src/guide/transitions-enterleave.md
> +### トランジションとアニメーションの併用
[note]
v2 では `トランジションとアニメーションを両方使う` だったが、ここだけ動詞なのもよくわからないので統一

2020-10-09 00:31 UTC, kazupon requested changes
1点翻訳漏れがあったので、そこをお願いします！

2020-10-09 00:31 UTC, kazupon commented on src/guide/transitions-enterleave.md
> +これを利用することによって、以下のようなより表現力のある動きをコーディネートすることができます。二つの要素がお互いの間でトランジションしていますが、そのお互いの大きさが同じであり、水平方向の 0 の位置で重なるため、一つの要素の動きの流れに見えます。このような細かな調整は、よりリアルなマイクロインタラクションの表現で役立ちます:
なるほど。いいと思います！

2020-10-10 07:58 UTC, potato4d commented
翻訳漏れ修正しました 🙇 
確認お願いいたします！

2020-10-10 13:43 UTC, kazupon approved these changes

2020-10-10 13:44 UTC, kazupon commented
@potato4d 
ありがとうございます！
マージしますね！

2020-10-10 13:44 UTC, merged