Transitions & Animation > Overview の翻訳
vuejs-jp/ja.vuejs.org pull request #104
Opened 2020-10-09 21:40 UTC by ryoAccount

resolve https://github.com/vuejs-jp/ja.vuejs.org/issues/21

https://v3.vuejs.org/guide/transitions-overview.html を翻訳しました。
レビューお願いします！

2020-10-10 07:50 UTC, potato4d requested changes
いくつかコメントしました！
textlint の CI を動く状態にしていただけますと幸いです 🙇‍♂️

2020-10-10 07:50 UTC, potato4d commented on src/guide/transitions-overview.md
> +イージングを調整することで多くのユニークな効果を得ることができ、アニメーションを非常にスタイリッシュにすることができます。 CSSを使用すると、3次のベジェ曲線のプロパティを調整して変形できます。 Lea Verou 氏によって作成された[遊び場](https://cubic-bezier.com/#.17,.67,.83,.67)は、イージングを探索するのに非常に役立ちます。
```suggestion
イージングを調整することで多くのユニークな効果を得ることができ、アニメーションを非常にスタイリッシュにすることができます。 CSSを使用すると、3次のベジェ曲線のプロパティを調整して変形できます。 Lea Verou 氏によって作成された[Playground](https://cubic-bezier.com/#.17,.67,.83,.67)は、イージングを探索するのに非常に役立ちます。
```

Playground は十分に浸透している言葉だと思うので、 `プレイグラウンド` あるいは英語そのままで問題かなと思います。どちらでも！

2020-10-10 07:50 UTC, potato4d commented on src/guide/transitions-overview.md
> +単純な UI トランジション、つまり中間を持たないとある状態から別の状態へのトランジションでは、0.1秒から0.4秒の間のタイミングを使用するのが一般的であり、ほとんどの人は _0.25秒_ がスイートスポットになる傾向があることに気付きます。 そのタイミングをすべてに使用できますか？ いいえ、そうではありません。 より長い距離を移動する必要があるもの、またはより多くのステップや状態変化があるも
`0.1秒から0.4秒の間`

多分この辺りで半角全角のエラーが出ると思うので、 `lang-ja` を取り込んだ上で `git rebase lang-ja` していただけますでしょうか :pray:

textlint が動作するようになります。

2020-10-10 07:50 UTC, potato4d commented on src/guide/transitions-overview.md
> +イージングはアニメーションの奥行きを伝える重要な方法です。 アニメーションの初心者がおかす最も一般的な間違いの1つは、序盤に `ease-in` を使用し、終盤に `ease-out` を使用することです。 実際には反対のことが必要です。
```suggestion
イージングはアニメーションの深みを伝える重要な方法です。 アニメーションの初心者がおかす最も一般的な間違いの1つは、序盤に `ease-in` を使用し、終盤に `ease-out` を使用することです。 実際には反対のことが必要です。
```

この `depth` は奥行きではなく、深みと訳すべきかなと思いました。

2020-10-10 13:51 UTC, kazupon approved these changes
レビュー 👀 しました。
翻訳内容は大丈夫です。

2020-10-10 22:30 UTC, ryoAccount commented on src/guide/transitions-overview.md
> +イージングを調整することで多くのユニークな効果を得ることができ、アニメーションを非常にスタイリッシュにすることができます。 CSSを使用すると、3次のベジェ曲線のプロパティを調整して変形できます。 Lea Verou 氏によって作成された[遊び場](https://cubic-bezier.com/#.17,.67,.83,.67)は、イージングを探索するのに非常に役立ちます。
Playground としました。

https://github.com/vuejs-jp/ja.vuejs.org/pull/104/commits/cbfddd57ebbd5fbf27dce423f77d9ecf8ca74913

2020-10-10 22:31 UTC, ryoAccount commented on src/guide/transitions-overview.md
> +イージングはアニメーションの奥行きを伝える重要な方法です。 アニメーションの初心者がおかす最も一般的な間違いの1つは、序盤に `ease-in` を使用し、終盤に `ease-out` を使用することです。 実際には反対のことが必要です。
「深み」に修正しました。

https://github.com/vuejs-jp/ja.vuejs.org/pull/104/commits/cbfddd57ebbd5fbf27dce423f77d9ecf8ca74913

2020-10-10 22:40 UTC, ryoAccount commented on src/guide/transitions-overview.md
> +単純な UI トランジション、つまり中間を持たないとある状態から別の状態へのトランジションでは、0.1秒から0.4秒の間のタイミングを使用するのが一般的であり、ほとんどの人は _0.25秒_ がスイートスポットになる傾向があることに気付きます。 そのタイミングをすべてに使用できますか？ いいえ、そうではありません。 より長い距離を移動する必要があるもの、またはより多くのステップや状態変化があるも
rebaseしました。
追加いただいた `lint:single` を実行して、エラーが出力されないことを確認しました。

```
yarn lint:single src/guide/transitions-overview.md
yarn run v1.19.1
$ textlint --rulesdir ./node_modules/textlint-checker-for-vuejs-jp-docs/rules/textlint-rule-vue-jp-docs -f pretty-error src/guide/transitions-overview.md
Done in 0.70s.
```

2020-10-10 22:44 UTC, ryoAccount commented
@potato4d 
指摘いただいた箇所、修正しました。

2020-10-17 14:00 UTC, potato4d approved these changes
返信遅くなりました :bow:
LGTM です！

2020-10-17 14:00 UTC, merged