Migration Guide > Filters の翻訳
vuejs-jp/ja.vuejs.org pull request #134
Opened 2020-10-20 13:10 UTC by fuku710

resolve #114 

https://v3.vuejs.org/guide/migration/filters.html の翻訳です

2020-10-21 12:12 UTC, potato4d requested changes
翻訳ありがとうございます！いくつかコメントしました👀

2020-10-21 12:12 UTC, potato4d commented on src/guide/migration/filters.md
> +# フィルター <MigrationBadges :badges="$frontmatter.badges" />
```suggestion
# フィルタ <MigrationBadges :badges="$frontmatter.badges" />
```

翻訳ルールとして、基本的には長音は伸ばさない形でお願いいたします！
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

2020-10-21 12:12 UTC, potato4d commented on src/guide/migration/filters.md
> +フィルターは Vue 3.0 で削除され、サポートされません。
```suggestion
フィルタは Vue 3.0 で削除され、サポートされません。
```

こちらも

2020-10-21 12:12 UTC, potato4d commented on src/guide/migration/filters.md
> +2.0 で開発者は共通のテキストフォーマットを適用するためにフィルターを使うことができました。
```suggestion
2.x で開発者は共通のテキストフォーマットを適用するためにフィルタを使うことができました。
```

- 2.0 -> 2.x
- フィルター -> フィルタ

2020-10-21 12:12 UTC, potato4d commented on src/guide/migration/filters.md
> +3.x ではフィルターは削除され、サポートされません。代わりに、関数の呼び出しか算出プロパティに置き換えることを推奨します。
```suggestion
3.x ではフィルタは削除され、サポートされません。代わりに、関数の呼び出しか算出プロパティに置き換えることを推奨します。
```

2020-10-21 12:12 UTC, potato4d commented on src/guide/migration/filters.md
> +フィルターを使う代わりに、算出プロパティか関数に置き換えることを推奨します。
```suggestion
フィルタを使う代わりに、算出プロパティか関数に置き換えることを推奨します。
```

2020-10-22 14:49 UTC, fuku710 commented
レビューありがとうございます！修正しました！

2020-10-26 03:32 UTC, potato4d approved these changes
LGTM!
ありがとうございます！

2020-10-26 03:32 UTC, merged