Migration Guide > key attribute の翻訳
vuejs-jp/ja.vuejs.org pull request #143
Opened 2020-10-22 21:05 UTC by ryoAccount

resolve https://github.com/vuejs-jp/ja.vuejs.org/issues/120

翻訳対象のファイルが fork 時点での vuejs.org にはないため、
本家の↓こちらを翻訳しています。
https://github.com/vuejs/docs-next/blob/master/src/guide/migration/key-attribute.md

2020-10-22 22:37 UTC, ryoAccount commented
@egurinko 
レビューお願い致します。

2020-10-26 03:31 UTC, potato4d requested changes
PRありがとうございます！

何点か、修正お願いします。

2020-10-26 03:31 UTC, potato4d commented on src/guide/migration/key-attribute.md
> +  - **速報:** 手動で `key` を指定する場合、各分岐は一意の `key` を使用する必要があります。 同じ `key` を意図的に使用して分岐を強制的に再利用することはできなくなりました。
```suggestion
  - **破壊的変更:** 手動で `key` を指定する場合、各分岐は一意の `key` を使用する必要があります。 同じ `key` を意図的に使用して分岐を強制的に再利用することはできなくなりました。
```

`Breaking` は破壊的変更(Breaking Changes)の意味なので、速報ではなく `破壊的` または `破壊的変更` で良いかと

2020-10-26 03:31 UTC, potato4d commented on src/guide/migration/key-attribute.md
> +- **速報:** `<template v-for>` における `key` は、`<template>` タグに配置する必要があります（子の要素ではない）
こちらも

2020-10-26 03:31 UTC, potato4d commented on src/guide/migration/key-attribute.md
> +`key` 属性はノードの ID を追跡するために Vue の仮想 DOM のアルゴリズムのヒントとして使用されます。 こうすることで Vue は既存のノードを再利用してパッチを適用できる時期と、ノードを並べ替えまたは再作成する必要がある時期を識別します。 詳細については、次のセクションを参照してください。
`special` の訳抜け？

2020-10-26 03:31 UTC, potato4d commented on src/guide/migration/key-attribute.md
> +上記の例は、Vue3.x でも機能します。 ただし、`v-if` / `v-else` / `v-else-if` 分岐で `key` 属性を使用することはお勧めしません。条件分岐で `key` を指定しない場合、一意となる `key` が自動的に生成されるようになったためです。
```suggestion
上記の例は、Vue3.x でも機能します。 ただし、`v-if` / `v-else` / `v-else-if` 分岐で `key` 属性を使用することはおすすめしません。条件分岐で `key` を指定しない場合、一意となる `key` が自動的に生成されるようになったためです。
```

漢字は開いたほうが読みやすいかと 📝

2020-10-26 03:31 UTC, potato4d commented on src/guide/migration/key-attribute.md
> +重大な変更は手動で `key` を指定する場合、各分岐は一意となる `key` を使用する必要があることです。ほとんどの場合、これらの `key` は削除できます。
breaking change は重大な変更ではなく破壊的変更です 🤖

2020-10-26 20:09 UTC, ryoAccount commented on src/guide/migration/key-attribute.md
> +  - **速報:** 手動で `key` を指定する場合、各分岐は一意の `key` を使用する必要があります。 同じ `key` を意図的に使用して分岐を強制的に再利用することはできなくなりました。
`破壊的変更` に修正しました
https://github.com/vuejs-jp/ja.vuejs.org/pull/143/commits/d05ecfdbaaa3e183ab13f5ca422c3763fd157bb1

2020-10-26 20:09 UTC, ryoAccount commented on src/guide/migration/key-attribute.md
> +- **速報:** `<template v-for>` における `key` は、`<template>` タグに配置する必要があります（子の要素ではない）
`破壊的変更` に修正しました
https://github.com/vuejs-jp/ja.vuejs.org/pull/143/commits/d05ecfdbaaa3e183ab13f5ca422c3763fd157bb1

2020-10-26 20:14 UTC, ryoAccount commented on src/guide/migration/key-attribute.md
> +`key` 属性はノードの ID を追跡するために Vue の仮想 DOM のアルゴリズムのヒントとして使用されます。 こうすることで Vue は既存のノードを再利用してパッチを適用できる時期と、ノードを並べ替えまたは再作成する必要がある時期を識別します。 詳細については、次のセクションを参照してください。
文頭を `特別な属性である key は～` に修正しました
https://github.com/vuejs-jp/ja.vuejs.org/pull/143/commits/d05ecfdbaaa3e183ab13f5ca422c3763fd157bb1

「key特別属性」だと違和感を感じたので、意図的に `special` を除いていました。

2020-10-26 20:15 UTC, ryoAccount commented on src/guide/migration/key-attribute.md
> +上記の例は、Vue3.x でも機能します。 ただし、`v-if` / `v-else` / `v-else-if` 分岐で `key` 属性を使用することはお勧めしません。条件分岐で `key` を指定しない場合、一意となる `key` が自動的に生成されるようになったためです。
`おすすめ` に修正しました。
https://github.com/vuejs-jp/ja.vuejs.org/commit/d05ecfdbaaa3e183ab13f5ca422c3763fd157bb1

2020-10-26 20:20 UTC, ryoAccount commented on src/guide/migration/key-attribute.md
> +重大な変更は手動で `key` を指定する場合、各分岐は一意となる `key` を使用する必要があることです。ほとんどの場合、これらの `key` は削除できます。
`破壊的変更` に修正しました。
https://github.com/vuejs-jp/ja.vuejs.org/commit/d05ecfdbaaa3e183ab13f5ca422c3763fd157bb1

てにをはも1ヶ所、見直しました。
`各分岐は一意となる` -> `各分岐に一意となる`

2020-10-26 20:21 UTC, ryoAccount commented
@potato4d 
レビューいただきありがとうございました。
指摘箇所を修正しました。
https://github.com/vuejs-jp/ja.vuejs.org/commit/d05ecfdbaaa3e183ab13f5ca422c3763fd157bb1

2020-10-27 06:36 UTC, potato4d approved these changes
LGTM!

2020-10-27 06:36 UTC, merged