Migration Guide > Slots Unification の翻訳
vuejs-jp/ja.vuejs.org pull request #146
Opened 2020-10-25 14:06 UTC by Katakuranatsumi

resolve #124 

https://v3.vuejs.org/guide/migration/slots-unification.html を翻訳しましたmm
レビューをお願いいたします🙏

2020-10-26 03:38 UTC, potato4d requested changes
翻訳ありがとうございます！

一点だけ修正お願いします。

2020-10-26 03:38 UTC, potato4d commented on src/guide/migration/slots-unification.md
> +- **速報**: `this.$scopedSlots` が削除されました
この Breaking は `Breaking Changes` つまりは破壊的変更を意味しているので、そちらで訳していただきたいです！

2020-10-26 04:01 UTC, Katakuranatsumi commented on src/guide/migration/slots-unification.md
> +- **速報**: `this.$scopedSlots` が削除されました
@potato4d 
ご確認ありがとうございましたmm
こちら 31c41f6 で修正しました🙇‍♀️

2020-10-27 06:34 UTC, potato4d approved these changes
LGTM!

2020-10-27 06:35 UTC, merged