Translate: Migration Guide > Data Option
vuejs-jp/ja.vuejs.org pull request #147
Opened 2020-10-26 16:23 UTC by nalpan

## Description of Problem
resolve #112 

## Proposed Solution
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/data-option.md を翻訳

## Additional Information

2020-10-26 16:28 UTC, nalpan commented
遅くなりました、よろしくお願いします。

2020-10-30 06:01 UTC, potato4d reviewed
翻訳ありがとうございます！

一点、コメントしました！

2020-10-30 06:01 UTC, potato4d commented on src/guide/migration/data-option.md
> +これは共有状態を持っているルートインスタンスに関してはある程度の利便性をもたらしましたが、ルートインスタンスでのみ可能であるという事実のため混乱を招きました。
```suggestion
これは共有状態を持っているルートインスタンスに関してはある程度の利便性をもたらしましたが、ルートインスタンスでのみ可能であるという事実のため混乱を招きました。
```

この shared の `ed` が `state` にかかっていて、 `状態が共有されている` と表現できる認識です。いかがでしょう？

2020-11-01 02:28 UTC, potato4d requested changes

2020-11-01 02:28 UTC, potato4d commented on src/guide/migration/data-option.md
> +# Data オプション <MigrationBadges :badges="$frontmatter.badges" />
こちらなんですが、 frontmatter 側を変更いただきたいですー。

2020-11-01 15:33 UTC, nalpan commented on src/guide/migration/data-option.md
> +# Data オプション <MigrationBadges :badges="$frontmatter.badges" />
https://github.com/vuejs-jp/ja.vuejs.org/pull/147/commits/e8cebe5fa571f758f75f5927abfd6b15ee340cf7
にて修正しました！

2020-11-01 15:33 UTC, nalpan commented on src/guide/migration/data-option.md
> +これは共有状態を持っているルートインスタンスに関してはある程度の利便性をもたらしましたが、ルートインスタンスでのみ可能であるという事実のため混乱を招きました。
https://github.com/vuejs-jp/ja.vuejs.org/pull/147/commits/9f895718f8afcd5c4174afef0c67779cbb8148b4
にて修正しました！

2020-11-01 15:34 UTC, nalpan commented
@potato4d 
レビューありがとうございます、各コメント対応しましたので確認お願いします。

2020-11-03 12:08 UTC, potato4d approved these changes
LGTM!
ありがとうございますー！

2020-11-03 12:08 UTC, merged