Translate: Migration Guide > KeyCode Modifiers
vuejs-jp/ja.vuejs.org pull request #156
Opened 2020-11-02 15:18 UTC by shimadev

## Description of Problem
resolve #121

## Proposed Solution

## Additional Information
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/keycode-modifiers.md
こちらの翻訳です
遅くなってすみません。レビューよろしくお願いします！

2020-11-03 11:53 UTC, potato4d requested changes
ありがとうございます！
いくつかコメントしました

2020-11-03 11:53 UTC, potato4d commented on src/guide/migration/keycode-modifiers.md
> +キーコードを利用している場合は、ケバブケース名を利用する方法に変更することを推奨します。
```suggestion
キーコードを利用している場合は、ケバブケースでの命名に変更することを推奨します。
```

日本語として少し違和感があるので、 naming を `命名` と訳した上で方法というのをそこに含めてしまうほうが読みやすいかなと！

2020-11-03 11:53 UTC, potato4d commented on src/guide/migration/keycode-modifiers.md
> +## 3.x 構文
```suggestion
## 3.x での構文
```

ここ申し訳ないのですが、 `での構文` で統一させてほしいです！

2020-11-03 11:53 UTC, potato4d commented on src/guide/migration/keycode-modifiers.md
> +## 2.x 構文
```suggestion
## 2.x での構文
```

ここ申し訳ないのですが、 `での構文` で統一させてほしいです！

2020-11-04 12:55 UTC, shimadev commented
レビューありがとうございます！
修正しました！

2020-11-10 16:12 UTC, potato4d approved these changes
LGTM!
ありがとうございました！

2020-11-10 16:12 UTC, merged