Contribute to the Docs > Documentation Style Guide の翻訳
vuejs-jp/ja.vuejs.org pull request #157
Opened 2020-11-03 10:39 UTC by Katakuranatsumi

resulve #130 

https://v3.vuejs.org/guide/contributing/doc-style-guide.html を翻訳しましたmm
お時間ある時にレビューをお願い致します🙏

2020-11-03 12:04 UTC, potato4d requested changes
基本良さそうですが、 VuePress の拡張文法の部分だけ修正お願いします！

2020-11-03 12:04 UTC, potato4d commented on src/guide/contributing/doc-style-guide.md
> +::: 情報
```suggestion
::: info
```

あーこの辺りなんですが、 `::: <type>` の形式は VuePress の拡張記法なので、基本的に変えないでください！

https://deploy-preview-157--vuejs-v3-ja-doc-preview.netlify.app/guide/contributing/doc-style-guide.html#%E3%82%A2%E3%83%A9%E3%83%BC%E3%83%88

2020-11-03 12:29 UTC, Katakuranatsumi commented on src/guide/contributing/doc-style-guide.md
> +::: 情報
@potato4d 
レビューありがとうございますmm
失礼しました、 205a995 で修正しました🙏

2020-11-04 03:46 UTC, potato4d approved these changes
LGTM!
ありがとうございましたー！

2020-11-04 03:46 UTC, merged