Migration Guide > Custom Directives の翻訳元ファイル更新と翻訳
vuejs-jp/ja.vuejs.org pull request #161
Opened 2020-11-08 03:11 UTC by daisuke85a

@potato4d @egurinko 

resolve #110

https://v3.vuejs.org/guide/migration/custom-directives.html の内容を翻訳しました！

翻訳前ファイルが古かったので、 https://github.com/vuejs/docs-next/blob/master/src/guide/migration/custom-directives.md から最新版をとってきて、それに対して翻訳しました。

ご確認をよろしくおねがいします！

2020-11-10 16:12 UTC, potato4d requested changes
細かいところ少しだけ良い感じにしてもらえればと思います。

全体、LGTMです！

2020-11-10 16:12 UTC, potato4d commented on src/guide/migration/custom-directives.md
> +- **unbind** - ディレクティブが削除されると呼び出されます。 1回だけ呼び出されます。
also が訳抜けしてそうなので、読みやすさ的にも `また、これは一度だけ呼び出されます` とすると良さそうでしょうか。

2020-11-10 16:12 UTC, potato4d commented on src/guide/migration/custom-directives.md
> +- **bind** - ディレクティブが要素にバインドされると発生します。一度だけ発生します。
```suggestion
- **bind** - ディレクティブが要素にバインドされると発生します。これは一度だけ発生します。
```

ここも一緒に読みやすくできると良いですかねー

2020-11-11 00:29 UTC, daisuke85a commented
@potato4d 
ご確認とご指摘をありがとうございます！
2つの指摘とも、ご提案どおり修正しました。読みやすくなりました！ありがとうございます！

お手数ですが、再度ご確認をお願いいたします🙏

2020-11-15 19:06 UTC, potato4d approved these changes
LGTM!
ありがとうございま下ー！

2020-11-15 19:07 UTC, merged