Migration Guide > Transition Class Change の翻訳
vuejs-jp/ja.vuejs.org pull request #163
Opened 2020-11-09 00:44 UTC by mmmommm

## Description of Problem
resolve #125 
## Proposed Solution

## Additional Information
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/transition.md
こちらを翻訳しました。
17行目の下位互換性という翻訳と31行目のenterとleaveが広義であるというという翻訳が正しいのか確認をお願いしたいです。
レビューよろしくお願いいたします。

2020-11-10 16:19 UTC, potato4d requested changes
いくつか変更コメント出させていただきました🙏

2020-11-10 16:19 UTC, potato4d commented on src/guide/migration/transition.md
> +v2.1.8 では `v-enter-to` トランジションクラスを導入して、 enter/leave トランジション間のタイミングのギャップに対応しました。しかし、下位互換性のために `v-enter` という名前はそのままになってしまっています。
```suggestion
v2.1.8 では `v-enter-to` トランジションクラスを導入して、 enter/leave トランジション間のタイミングのギャップに対応しました。しかし、後方互換性のために `v-enter` という名前はそのままになってしまっています。
```

こちら description にありましたが、認識は問題有りません！
ただ一般的には後方互換性と呼ばれるので、こちらのほうがベターですかねー。

2020-11-10 16:19 UTC, potato4d commented on src/guide/migration/transition.md
> +これは _enter_ と _leave_ が広義であり、クラスのフックと同じ命名規則を使っていないため、混乱を招いてしまっています。
より良い言い回しはあるかもしれませんが、意味合いとしては主語が大きいみたいなことだと思うので、こちらも広義で大丈夫かなとは思います。
が、日本語にはあまりない言い回しなので、こういうケースどうするかは翻訳ガイドラインでまた規定すべきですね……ありがとうございます！

2020-11-10 16:19 UTC, potato4d commented on src/guide/migration/transition.md
> +## 3.x アップデート
```suggestion
## 3.x でのアップデート
```

2020-11-10 16:19 UTC, potato4d commented on src/guide/migration/transition.md
> +- `enter-class` は `enter-from-class` に名前が変更されます。（レンダー関数やJSXでは `leaveFromClass` と書くことができます）
```suggestion
- `leave-class` は `leave-from-class` に名前が変更されます。（描画関数やJSXでは `leaveFromClass` と書くことができます）
- `enter-class` は `enter-from-class` に名前が変更されます。（描画関数やJSXでは `leaveFromClass` と書くことができます）
```

v2.x 時代から描画関数という名称を使っているので、こちらでお願いします 🙇‍♂️

2020-11-10 20:01 UTC, mmmommm commented
レビューありがとうございます、修正しました。
https://github.com/vuejs-jp/ja.vuejs.org/pull/155
こちらのPRで統一されていたので13行目を
`2.x での構文`とさせていただきました、問題あれば戻しますのでまた教えていただきたいです。

2020-11-15 19:05 UTC, potato4d approved these changes
LGTMです！
ありがとうございました :bow:

2020-11-15 19:05 UTC, merged