Translate Style Guide / Priority A
vuejs-jp/ja.vuejs.org pull request #166
Opened 2020-11-14 08:40 UTC by t0yohei

## Description of Problem
#138 の `Priority A` の翻訳

## Proposed Solution

## Additional Information
本日(2020/11/14)時点で最新のコミットを元に翻訳を行いました。
https://github.com/vuejs/docs-next/blob/0e5b6786d613eaa931f96310e6f5c48a2974a9cd/src/style-guide/README.md

2020-11-17 14:15 UTC, potato4d requested changes
typo についての request changes と IMO をいくつか書きました。
ご確認いただければと思いますー！

2020-11-17 14:15 UTC, potato4d commented on src/style-guide/README.md
> +全ての HTML 要素は 1 単語なので、このルールを守ることで既に存在 HTML 要素や将来定義される HTML 要素との[衝突を防止することができます](http://w3c.github.io/webcomponents/spec/custom/#valid-custom-element-name)。
```suggestion
全ての HTML 要素は 1 単語なので、このルールを守ることで既に存在する HTML 要素や将来定義される HTML 要素との[衝突を防止することができます](http://w3c.github.io/webcomponents/spec/custom/#valid-custom-element-name)。
```

typo ですかね

2020-11-17 14:15 UTC, potato4d commented on src/style-guide/README.md
> +- コンポーネントの API が文書化されるため、そのコンポーネントの使用方法が簡単に確認できます。
```suggestion
- コンポーネントの API が明文化されるため、そのコンポーネントの使用方法が簡単に確認できます。
```

文書化ときくとあまりイメージしづらく、型定義などでよく言及される「型はドキュメント」の意味だと思うので、明文化や明確化という形で多少意訳しても良いかもしれないですね

2020-11-17 14:15 UTC, potato4d commented on src/style-guide/README.md
> +// プロトタイピングの時だけ OK
```suggestion
// プロトタイピングの時に限り OK
```

2020-11-17 14:15 UTC, potato4d commented on src/style-guide/README.md
> +**アプリケーションにとって、トップレベルの `App` コンポーネントとレイアウトコンポーネントのスタイルはグローバルである可能性がありますが、他のすべてのコンポーネントは常にスコープされているべきです。**
```suggestion
**アプリケーションにとって、トップレベルの `App` コンポーネントとレイアウトコンポーネントのスタイルはグローバルである可能性がありますが、他のすべてのコンポーネントは常にスコープされているべきです。**
```

be A は A であるべき/すべきですが、スコープされているという言葉が日本語になさそうなので、 scoped であるべきで良いかなーと思いました。
IMOなので、意見がほしいです！

2020-11-17 16:06 UTC, t0yohei commented on src/style-guide/README.md
> +**アプリケーションにとって、トップレベルの `App` コンポーネントとレイアウトコンポーネントのスタイルはグローバルである可能性がありますが、他のすべてのコンポーネントは常にスコープされているべきです。**
ありがとうございます！
確かに、違和感ありますね...
`スコープ化されているべき` とかもありかなーと思ったのですが、あまりそう言う表現使わないですかね...？ 🤔 
`scoped であるべき` or `スコープ化されているべき` で potato4d さんの違和感が少ない方を採用できればと思います！ 👍

2020-11-19 12:57 UTC, potato4d commented on src/style-guide/README.md
> +**アプリケーションにとって、トップレベルの `App` コンポーネントとレイアウトコンポーネントのスタイルはグローバルである可能性がありますが、他のすべてのコンポーネントは常にスコープされているべきです。**
スコープ化されているべきでも良いかもです！
t0yohei さんがよりしっくりくるほうで大丈夫です！

2020-11-21 02:11 UTC, t0yohei commented
@potato4d 
レビューありがとうございます！指摘いただいていた部分修正しました！
https://github.com/vuejs-jp/ja.vuejs.org/pull/166/commits/ec6a458915eadc0560cdfc388ec946b044faa285

2020-11-21 09:49 UTC, potato4d approved these changes
LGTM!
ありがとうございました！

2020-11-21 09:50 UTC, merged