doc: Translate API Configuration in Reference
vuejs-jp/ja.vuejs.org pull request #178
Opened 2020-12-07 12:58 UTC by potato4d

This PR is part of #177 

## About

API Reference > API Config を翻訳しました。

## Note

サンプルコードの typo は[本家に PR を送っています](https://github.com/vuejs/docs-next/pull/736)が、どのみち一緒なのでこちらでも直しています。

2020-12-08 00:38 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
確認お願します！

2020-12-08 00:38 UTC, kazupon commented on src/api/application-config.md
> +  // `trace` は、コンポーネントのヒエラルキートレースです。
hierarchy は 「階層」に訳したほうがわかりやすそうです。

2020-12-08 02:01 UTC, potato4d commented on src/api/application-config.md
> +  // `trace` は、コンポーネントのヒエラルキートレースです。
お、了解です。
一応意図としては Unity の階層ツリーが日本語版でも「ヒエラルキー」と言及されていて、階層構造についてヒエラルキーの言葉を利用するのは一般的かなと思っていますが、どうでしょう（特にこだわりはないので割とどちらでも大丈夫ではあります！）

https://docs.unity3d.com/ja/2018.4/Manual/Hierarchy.html

2020-12-08 03:48 UTC, kazupon commented on src/api/application-config.md
> +  // `trace` は、コンポーネントのヒエラルキートレースです。
そうですね。原則翻訳できるところは翻訳しておきたいので、お願いしたいです。
```suggestion
  // `trace` は、コンポーネント階層のトレースです。
```

2020-12-22 04:52 UTC, potato4d commented
@kazupon 
すみません取り込み押し忘れてました 🙇‍♂️ 
問題なければマージお願いしますー。

2020-12-22 04:54 UTC, merged

2020-12-22 04:55 UTC, kazupon commented
@potato4d merged