Migration > Async Components の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #237
Opened 2021-04-07 09:59 UTC by naokie

ref. #203

Migration > Async Components を本家の master に追従しました。

ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/async-components.md

前回からの差分
https://github.com/vuejs/docs-next/commit/9d48e280d3862fc951d1c821cd4e863a7b56efba#diff-810cfc1a42d27b7b308a29e3c5c72f09aff1279ff9b91ceef811e2b1d2beb06b

close #203

2021-04-07 14:03 UTC, kazupon requested changes
@naokie 
ありがとうございます！

以下のcommitが漏れているようです。

https://github.com/vuejs/docs-next/commit/639940b6154e318b0b26fd4a394defaa82eb45ba#diff-810cfc1a42d27b7b308a29e3c5c72f09aff1279ff9b91ceef811e2b1d2beb06b
https://github.com/vuejs/docs-next/commit/2283eca469cbc4a9155047d1ad86ac8e57c7dd0c#diff-810cfc1a42d27b7b308a29e3c5c72f09aff1279ff9b91ceef811e2b1d2beb06b
https://github.com/vuejs/docs-next/commit/fcb40f337c34e38bd9971bc781248c39b73c58d2#diff-810cfc1a42d27b7b308a29e3c5c72f09aff1279ff9b91ceef811e2b1d2beb06b
https://github.com/vuejs/docs-next/commit/1b6e5757f4bb0056b39da82f0cb450232ff4fb5f#diff-810cfc1a42d27b7b308a29e3c5c72f09aff1279ff9b91ceef811e2b1d2beb06b

2021-04-08 10:59 UTC, naokie commented
@kazupon レビューありがとうございます。

それは機械的に抽出した差分でしょうか？
日本語訳の First commit ab73be8 でほぼ最新まで追従できていたので、残った差分をは最新の1件のみでした。

なにか認識ズレていたら指摘してもらえますか？

2021-04-09 00:01 UTC, kazupon approved these changes

2021-04-09 00:02 UTC, kazupon commented
@naokie 
すいません。こちらの確認の仕方が間違っていました。 🙇 
大変失礼しました。
今回対応して頂いた分で大丈夫でした。

ありがとうございました！

2021-04-09 00:02 UTC, merged