Migration > Attrs Includes Class Style の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #238
Opened 2021-04-09 05:12 UTC by naokie

## Description of Problem

Migration > Attrs Includes Class Style を本家の master に追従しました。
ref. #205

## Proposed Solution

対象ファイルが存在しなかったため、新規の作成です。

## Additional Information

close #205

2021-04-09 17:02 UTC, kazupon requested changes
レビューしました！1点だけ確認するところがあるので、お願いします！ 🙏

2021-04-09 17:02 UTC, kazupon commented on src/guide/migration/attrs-includes-class-style.md
> +- But `class` and `style`, not being part of `$attrs`, will still be applied to the component's root element:
この行は、次の行の訳したものですが、残ってしまっているようです。

2021-04-10 08:00 UTC, naokie commented on src/guide/migration/attrs-includes-class-style.md
> +- But `class` and `style`, not being part of `$attrs`, will still be applied to the component's root element:
ありがとうございます。
すっかり見落としていました。

2021-04-10 09:00 UTC, kazupon approved these changes
ありがとうございます！

2021-04-10 09:01 UTC, kazupon commented
あ、コンフリクトが起きているようです！

2021-04-10 11:22 UTC, naokie commented
サイドバーのメニュー部分、ちょうど連続して未翻訳のページ追加のPR出したからですね。
修正しておきました。

2021-04-10 13:08 UTC, kazupon commented
ありがとうございます！

2021-04-10 13:08 UTC, merged