Migration > Emits Option の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #243
Opened 2021-04-09 13:28 UTC by naokie

## Description of Problem

Migration > Emits Option を本家の master に追従しました。
ref. #210

## Proposed Solution

対象ファイルが存在しなかったため、新規の作成です。

## Additional Information

close #210

2021-04-09 17:20 UTC, kazupon requested changes
レビューしました。確認お願いします！

2021-04-09 17:20 UTC, kazupon commented on src/guide/migration/emits-option.md
> +各コンポーネントから発行されたすべてのイベントを、 `emits` を使って記録することを強くお勧めします。
原文は、
```
It is highly recommended that you document all of the events emitted by each of your components using emits.
```
ですが、`emitted` の訳は記録ではなくて、ここでは `発行する` と訳した方が自然かと思います。これを考慮すると以下になるかと思います。

```suggestion
各コンポーネントから発行されたすべてのイベントを、 `emits` を使って発行することを強くお勧めします。
```

2021-04-10 08:04 UTC, naokie commented on src/guide/migration/emits-option.md
> +各コンポーネントから発行されたすべてのイベントを、 `emits` を使って記録することを強くお勧めします。
一方で emits を正しく翻訳しておきながら、おかしなことしてました。
ありがとうございます！

2021-04-10 08:59 UTC, kazupon approved these changes
対応ありがとうございます！

2021-04-10 08:59 UTC, merged