Migration > Events Api の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #244
Opened 2021-04-10 12:20 UTC by naokie

## Description of Problem

Migration > Events Api を本家の master に追従しました。
ref. #211

## Proposed Solution

本家の更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/events-api.md

前回からの差分
https://github.com/vuejs/docs-next/commit/cf59d27302dd97d1e741cfba12485bbd4600c3a1#diff-df28d8fa80ea53d422708b42d11e0a82001d9a97543715759ddbaccc3863273e
https://github.com/vuejs/docs-next/commit/4797c24752e7759a14f96b4191026223ce692858#diff-df28d8fa80ea53d422708b42d11e0a82001d9a97543715759ddbaccc3863273e

## Additional Information

close #211

2021-04-10 13:30 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2021-04-10 13:30 UTC, kazupon commented on src/guide/migration/events-api.md
> +Vue 3 では、これらの API を使用して、コンポーネント内からコンポーネント自身が発行したイベントをリッスンすることはできなくなりました。そのユースケースのための移行パスはありません。
`リッスン` は `購読` にしておきましょうか。
```suggestion
Vue 3 では、これらの API を使用して、コンポーネント内からコンポーネント自身が発行したイベントを購読することはできなくなりました。そのユースケースのための移行パスはありません。
```

2021-04-10 13:30 UTC, kazupon commented on src/guide/migration/events-api.md
> +ただし、イベントハブパターンは、イベントエミッタインタフェースを実装した外部ライブラリを使用することで置き換えることができます。例えば、[mitt](https://github.com/developit/mitt) や [tiny-emitter](https://github.com/scottcorgan/tiny-emitter) などです。
Event Emitter のような技術用語は JavaScript 界隈ではパターンとして一般的になっているので訳さなくても良さそうです。あえて訳すのなら括弧付きで注釈気味ですかね。
(本家の記載が `Event Emitter` になっていないのが気になる... Event Hub も `eventHub` になっていて気になる)

```suggestion
ただし、EventHub (イベントハブ) パターンは、Event Emitter (イベントエミッタ) インタフェースを実装した外部ライブラリを使用することで置き換えることができます。例えば、[mitt](https://github.com/developit/mitt) や [tiny-emitter](https://github.com/scottcorgan/tiny-emitter) などです。
```

2021-04-10 13:30 UTC, kazupon commented on src/guide/migration/events-api.md
> +これは Vue 2 と同じようなイベントエミッタ API を提供します。
ここも先と同じですね。
```suggestion
これは Vue 2 と同じような Event Emitter API を提供します。
```

2021-04-10 13:30 UTC, kazupon commented on src/guide/migration/events-api.md
> +These methods may also be supported in a future compatibility build of Vue 3.
ここ、原文削除するの漏れてます。

独り言:
今気がついたけど、今 Evan が実装している v2-compat について書いてあったんですね...
https://github.com/vuejs/vue-next/tree/v2-compat

2021-04-11 04:36 UTC, naokie commented on src/guide/migration/events-api.md
> +ただし、イベントハブパターンは、イベントエミッタインタフェースを実装した外部ライブラリを使用することで置き換えることができます。例えば、[mitt](https://github.com/developit/mitt) や [tiny-emitter](https://github.com/scottcorgan/tiny-emitter) などです。
あー、わかります。
単語の先頭が大文字になっていれば用語として、そのまま残すような判断できるんですが難しいですね。

2021-04-11 04:41 UTC, naokie commented on src/guide/migration/events-api.md
> +These methods may also be supported in a future compatibility build of Vue 3.
あ、また削除忘れが 😳

2021-04-11 04:54 UTC, naokie commented on src/guide/migration/events-api.md
> +These methods may also be supported in a future compatibility build of Vue 3.
先日の定例でちょっと話題にしていた v2-compat ですね。それに気づくとはちょっと興奮しました。
なるほど... Event Emitter まわりも互換性残すもの追加されてる。
https://github.com/vuejs/vue-next/commit/db098056884dcd73ff837c8256da3ed4d32a3d87

2021-04-11 04:55 UTC, naokie commented
レビューポイントの修正、ひととおり終わりました。
Suggestion 助かります！

2021-04-11 14:45 UTC, kazupon approved these changes

2021-04-11 14:45 UTC, kazupon commented
ありがとうございます！マージしますね！

2021-04-11 14:45 UTC, merged