Migration > Filters の翻訳の追従
vuejs-jp/ja.vuejs.org pull request #245
Opened 2021-04-10 12:56 UTC by naokie

## Description of Problem

Migration > Filters を本家の master に追従しました。
ref. #212

## Proposed Solution

本家の更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/filters.md

前回からの差分
https://github.com/vuejs/docs-next/commit/f15e2f706068fffdd06c23a0fef8a9d92e108110#diff-dd4e65deb15a7ff2b00f8c9ac47f8c0a080eafcc3a83aeeda9e0124b542a8560
https://github.com/vuejs/docs-next/commit/08abb47557c919d862a70b6322b4e336c5105025#diff-dd4e65deb15a7ff2b00f8c9ac47f8c0a080eafcc3a83aeeda9e0124b542a8560

## Additional Information

close #212

2021-04-10 13:20 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2021-04-10 13:20 UTC, kazupon commented on src/guide/migration/filters.md
> +もしグローバルに登録されてからアプリ全体で使用されているフィルタを使用している場合、それを個々のコンポーネントで算出プロパティやメソッドに置き換えるのは不便でしょう。
原文通り約すと日本語的にわかりづらくなるので、意訳気味に以下にしておきましょうか。

```suggestion
もし、グローバルにフィルタを登録していて、そしてアプリケーション全体でそのフィルタを使用している場合、そのフィルタを個々のコンポーネントで算出プロパティやメソッドに置き換えるのは不便でしょう。
```

2021-04-11 04:57 UTC, naokie commented on src/guide/migration/filters.md
> +もしグローバルに登録されてからアプリ全体で使用されているフィルタを使用している場合、それを個々のコンポーネントで算出プロパティやメソッドに置き換えるのは不便でしょう。
ありがとうございます！
訳しづらい箇所だったので、助かりました。

2021-04-11 14:46 UTC, kazupon approved these changes

2021-04-11 14:46 UTC, merged