Migration > Listeners Removed の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #248
Opened 2021-04-13 11:00 UTC by naokie

## Description of Problem

Migration > Listeners Removed を本家の master に追従しました。
ref. #221 

## Proposed Solution

対象ファイルが存在しなかったため、新規の作成です。

## Additional Information

close #221

2021-04-13 17:42 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2021-04-13 17:42 UTC, kazupon commented on src/guide/migration/listeners-removed.md
> +`$listeners` オブジェクトは Vue 3 ですべて削除されました。イベントリスナは `$attrs` の一部になりました。
`すべて` に該当する英語ってありましたっけ？

2021-04-14 11:10 UTC, naokie commented on src/guide/migration/listeners-removed.md
> +`$listeners` オブジェクトは Vue 3 ですべて削除されました。イベントリスナは `$attrs` の一部になりました。
https://github.com/vuejs/docs-next/blob/master/src/guide/migration/listeners-removed.md#L11
ぜんぜんそんな単語ありませんでした！気づいてもらって、ありがとうございます。
まだ翻訳の精度低いですね…、がんばります 💪

2021-04-14 14:44 UTC, kazupon approved these changes

2021-04-14 14:44 UTC, kazupon commented
修正ありがとうございます！merge します！

2021-04-14 14:44 UTC, merged