Guide > Data Properties and Methods の翻訳
vuejs-jp/ja.vuejs.org pull request #268
Opened 2021-04-20 12:18 UTC by naokie

## Description of Problem

Guide > Data Properties and Methods の翻訳を追加しました。
https://v3.vuejs.org/guide/data-methods.html
https://github.com/vuejs/docs-next/blob/master/src/guide/data-methods.md

## Proposed Solution

対象ファイルが存在しなかったため、新規の作成です。

## Additional Information

2021-04-20 12:21 UTC, naokie commented on src/guide/data-methods.md
> +### Debounce (デバウンス) と Throttle (スロットル)
debounce も throttle も、カタカナ表記にしていることさえ、あまりなさそうですが…
見出しで並列表記しておきつつ、本文中ではカタカナにしてみました。

2021-04-20 12:23 UTC, naokie commented on src/guide/data-methods.md
> +また、テンプレートから直接メソッドを呼び出すこともできます。後で説明しますが、通常は変わりに [算出プロパティ](computed.html) を使うのがよいです。しかし、メソッドを使うことは算出プロパティが実行可能なオプションではない場合に役に立ちます。テンプレートが JavaScript の式をサポートしていれば、どこでもメソッドを呼び出すことができます:
> computed properties aren't a viable option

いまいち伝わりづらい感じですが、直訳するしかできなかったです。

2021-04-20 13:45 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
確認お願いします！

2021-04-20 13:45 UTC, kazupon commented on src/guide/data-methods.md
> +新しいプロパティを `data` に含めずに、コンポーネントのインスタンスに直接追加することはできます。しかし、このプロパティはリアクティブな `$data` オブジェクトによって裏付けされていないので、 [Vue のリアクティブシステム](reactivity.html) によって、自動的に追跡されることはありません。
`backed by` の訳ですが、ここでは `支援する` 的な意味合いを持ったものだ思います。なので、以下な感じになると思います。
```suggestion
新しいプロパティを `data` に含めずに、コンポーネントのインスタンスに直接追加することはできます。しかし、このプロパティはリアクティブな `$data` オブジェクトによって支援されていないので、 [Vue のリアクティブシステム](reactivity.html) によって、自動的に追跡されることはありません。
```

2021-04-20 13:45 UTC, kazupon commented on src/guide/data-methods.md
> +Vue は、コンポーネントのインスタンスを介して自身のビルトイン API を公開する際に、 `$` をプレフィックスに使います。 また、内部プロパティのために `_` を予約しています。トップレベルの `data` プロパティの名前に、これらの文字からはじまる名前を使うことは避けるべきです。
`Vue uses a $ prefix` ですが、以下な感じの方が読みやすいと思います。
```suggestion
Vue は、コンポーネントのインスタンスを介して自身のビルトイン API を公開する際に、 `$` をプレフィックスとして使います。 また、内部プロパティのために `_` を予約しています。トップレベルの `data` プロパティの名前に、これらの文字からはじまる名前を使うことは避けるべきです。
```

2021-04-20 13:45 UTC, kazupon commented on src/guide/data-methods.md
> +### Debounce (デバウンス) と Throttle (スロットル)
おおいいですね！ 👍 

このケースのように、英語をベースに括弧付でカタカナを表記する場合は、以降では英語でいいと思います。ここで読者は読み方が分かって、以降は読めると思うので。

2021-04-21 03:39 UTC, naokie commented on src/guide/data-methods.md
> +新しいプロパティを `data` に含めずに、コンポーネントのインスタンスに直接追加することはできます。しかし、このプロパティはリアクティブな `$data` オブジェクトによって裏付けされていないので、 [Vue のリアクティブシステム](reactivity.html) によって、自動的に追跡されることはありません。
そうですね。大きく2つの訳があって「裏付けされている」か「支持されている」のどちらか悩みました。
後者の訳にして「支えられている」ぐらいの簡単な日本語にしますね。

2021-04-21 03:41 UTC, naokie commented on src/guide/data-methods.md
> +Vue は、コンポーネントのインスタンスを介して自身のビルトイン API を公開する際に、 `$` をプレフィックスに使います。 また、内部プロパティのために `_` を予約しています。トップレベルの `data` プロパティの名前に、これらの文字からはじまる名前を使うことは避けるべきです。
ありがとうございます。このまま使います。

2021-04-21 10:00 UTC, naokie commented
レビューポイントの反映しました。

2021-04-22 00:23 UTC, kazupon approved these changes

2021-04-22 00:23 UTC, kazupon commented
確認しました！ありがとうございます！
マージしますね！

2021-04-22 00:23 UTC, merged