Guide> Production Deployment の翻訳
vuejs-jp/ja.vuejs.org pull request #270
Opened 2021-04-21 11:06 UTC by naokie

## Description of Problem

Guide > Production Deployment の翻訳を追加しました。
https://v3.vuejs.org/guide/tooling/deployment.html
https://github.com/vuejs/docs-next/blob/master/src/guide/tooling/deployment.md

## Proposed Solution

対象ファイルが存在しなかったため、新規の作成です。

## Additional Information

カタカナのままがよいものが多くなってしまったので、ツッコミ大歓迎です。

2021-04-21 11:08 UTC, naokie commented on src/guide/tooling/deployment.md
> +DOM 内のテンプレートや、 JavaScript 内のテンプレートリテラルを使う場合、テンプレートからレンダリング関数へのコンパイルは実行時に行われます。ほとんどの場合、この方法で十分な速度が得られますが、アプリケーションがパフォーマンスを重視される場合は避けたほうがよいです。
in-JavaScript template strings -> JavaScript のテンプレートリテラル
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals
以前 template strings と呼ばれていた名残だと思うので、ここではテンプレートリテラルにしておきました。

2021-04-21 11:11 UTC, naokie commented on src/guide/tooling/deployment.md
> +DOM 内のテンプレートや、 JavaScript 内のテンプレートリテラルを使う場合、テンプレートからレンダリング関数へのコンパイルは実行時に行われます。ほとんどの場合、この方法で十分な速度が得られますが、アプリケーションがパフォーマンスを重視される場合は避けたほうがよいです。
on the fly -> 実行時に
https://ejje.weblio.jp/content/%E3%82%AA%E3%83%B3%E3%82%B6%E3%83%95%E3%83%A9%E3%82%A4
コンピュータ用語の方なのでこちらに。

2021-04-21 11:12 UTC, naokie commented on src/guide/tooling/deployment.md
> +単一ファイルコンポーネントを使う場合、コンポーネント内の CSS は JavaScript を介して `<style>` タグとして動的に差し込まれます。これにはわずかなランタイムコストがかかります。また、サーバーサイドレンダリングを使っている場合は、「瞬間的にスタイルのないコンテンツ」を引き起こします。同じファイルにすべてのコンポーネントの CSS を抽出することで、このような問題を回避して、
Single-File Components -> 単一ファイルコンポーネント
身近な人だと「SFC」「シングルファイルコンポーネント」で通じちゃってるのですが、公式の日本語訳としてはこれで統一でしょうか？

2021-04-22 00:40 UTC, kazupon requested changes
レビューしました！
確認お願いします！

2021-04-22 00:40 UTC, kazupon commented on src/guide/tooling/deployment.md
> +フルビルドを使う場合、つまりビルドツールを使わずに script タグで Vue を直接含める場合は、必ず minifiled バージョンを本番で使ってください。これは、 [インストールガイド](/guide/installation.html#cdn) に記載されています。
`minified version` は以下な感じに訳した方が、初心者フレンドリーでいいかと思います。
```suggestion
フルビルドを使う場合、つまりビルドツールを使わずに script タグで Vue を直接含める場合は、必ず 縮小バージョン (minified version:コードが小さくされたバージョン) を本番で使ってください。これは、 [インストールガイド](/guide/installation.html#cdn) に記載されています。
```

2021-04-22 00:40 UTC, kazupon commented on src/guide/tooling/deployment.md
> +Webpack や Browserify などのビルドツールを使う場合は、プロダクションモードは Vue のソースコード内の `process.env.NODE_ENV` で決定され、デフォルトでは開発モードになります。どちらのビルドツールも、 Vue のプロダクションモードを有効にするために、この変数を上書きする方法を提供しており、警告はビルド中に Minifier (圧縮・軽量化) によって
独り言: 
原文も `Browserify` って書いてあるのか。(今、Vue アプリケーションを Browserify でバンドルしているのないと思うんだけど... vueify もメンテしてないし https://github.com/vuejs/vueify)

2021-04-22 00:40 UTC, kazupon commented on src/guide/tooling/deployment.md
> +#### Browserify
独り言:
あれ、Browsery についてまだ載せてる。
何か意図があるのかな。 🤔

2021-04-22 00:40 UTC, kazupon commented on src/guide/tooling/deployment.md
> +DOM 内のテンプレートや、 JavaScript 内のテンプレートリテラルを使う場合、テンプレートからレンダリング関数へのコンパイルは実行時に行われます。ほとんどの場合、この方法で十分な速度が得られますが、アプリケーションがパフォーマンスを重視される場合は避けたほうがよいです。
いいと思います！ 👍

2021-04-22 00:40 UTC, kazupon commented on src/guide/tooling/deployment.md
> +単一ファイルコンポーネントを使う場合、コンポーネント内の CSS は JavaScript を介して `<style>` タグとして動的に差し込まれます。これにはわずかなランタイムコストがかかります。また、サーバーサイドレンダリングを使っている場合は、「瞬間的にスタイルのないコンテンツ」を引き起こします。同じファイルにすべてのコンポーネントの CSS を抽出することで、このような問題を回避して、
はい！ 日本語のドキュメントなので、 `単一ファイルコンポーネント` でお願いします！

2021-04-22 10:17 UTC, naokie commented on src/guide/tooling/deployment.md
> +フルビルドを使う場合、つまりビルドツールを使わずに script タグで Vue を直接含める場合は、必ず minifiled バージョンを本番で使ってください。これは、 [インストールガイド](/guide/installation.html#cdn) に記載されています。
ありがとうございます！ Suggestion そのまま取り込みます。

2021-04-22 10:18 UTC, naokie commented on src/guide/tooling/deployment.md
> +Webpack や Browserify などのビルドツールを使う場合は、プロダクションモードは Vue のソースコード内の `process.env.NODE_ENV` で決定され、デフォルトでは開発モードになります。どちらのビルドツールも、 Vue のプロダクションモードを有効にするために、この変数を上書きする方法を提供しており、警告はビルド中に Minifier (圧縮・軽量化) によって
自分も翻訳していて、まだ Browserify？って思っちゃいました。
バンドラーもメンテしてないんですね。これはちょと本家に提案をコミットするチャンスかな。

2021-04-22 10:19 UTC, naokie commented
レビューポイントの反映しました

2021-04-22 10:46 UTC, kazupon commented on src/guide/tooling/deployment.md
> +Webpack や Browserify などのビルドツールを使う場合は、プロダクションモードは Vue のソースコード内の `process.env.NODE_ENV` で決定され、デフォルトでは開発モードになります。どちらのビルドツールも、 Vue のプロダクションモードを有効にするために、この変数を上書きする方法を提供しており、警告はビルド中に Minifier (圧縮・軽量化) によって
そうですね。これはコミットチャンスですね。
結構、大きく変わる部分なので、英語でやり取りが大変だと思いますが。

Browserify の代わりの載せるとしたら、Vite でしょうかね。

2021-04-22 10:53 UTC, kazupon approved these changes

2021-04-22 10:53 UTC, merged