Guide > Application & Component Instances の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #273
Opened 2021-04-23 12:43 UTC by naokie

## Description of Problem

Guide > Application & Component Instances の翻訳を master に追従しました。
https://v3.vuejs.org/guide/instance.html
https://github.com/vuejs/docs-next/blob/master/src/guide/instance.md

## Proposed Solution

ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/instance.md

前回からの差分
https://github.com/vuejs/docs-next/commit/ab4fac3c611fd3fa21caf3d3110a0ed84338952c#diff-387585561f9e33948afabefc665f07bc1c46123db320dc1c1899d25f3d723c0b
https://github.com/vuejs/docs-next/commit/aa76cd102a73d05e580dbe1d7f421b3047504d0d#diff-387585561f9e33948afabefc665f07bc1c46123db320dc1c1899d25f3d723c0b

## Additional Information

2021-04-23 12:45 UTC, naokie commented on src/guide/instance.md
> +アプリケーションインスタンスは、そのアプリケーション内のコンポーネントが使えるグローバル（コンポーネント、ディレクティブ、プラグインなど）を登録するために使われます。詳しいことはガイドの後半で説明しますが、簡単な例をあげると:
> The application instance is used to register 'globals' that can then be used by components within that application.
「globals」が訳すの難しかったので、次のサンプルソースを元にした例をカッコ書きで追加しました。

2021-04-23 12:47 UTC, naokie commented on src/guide/instance.md
> +アプリケーションインスタンスが公開するほとんどのメソッドは、同じインスタンスを返すので、チェーンすることができます:
「chaining」
メソッドチェーンとか、プロトタイプチェーンとかあるので、カタカナでチェーンするにしました。

2021-04-23 14:23 UTC, kazupon requested changes
レビューしました。
いくつかコメントしたので、確認お願いします！

2021-04-23 14:23 UTC, kazupon commented on src/guide/instance.md
> +アプリケーションインスタンスは、そのアプリケーション内のコンポーネントが使えるグローバル（コンポーネント、ディレクティブ、プラグインなど）を登録するために使われます。詳しいことはガイドの後半で説明しますが、簡単な例をあげると:
いいと思います 👍

2021-04-23 14:23 UTC, kazupon commented on src/guide/instance.md
> +アプリケーションインスタンスが公開するほとんどのメソッドは、同じインスタンスを返すので、チェーンすることができます:
👍

2021-04-23 14:23 UTC, kazupon commented on src/guide/instance.md
> +このガイドでは `data` プロパティについて説明しました。 `data` で定義されたプロパティは、コンポーネントインスタンスを介して公開されます:
`Earlier in the guide we met data properties. ` の訳ですが、`Earlier in` が抜けているので、以下のような感じな訳でどうでしょうか。
```suggestion
このガイドの前半で `data` プロパティについて説明しました。 `data` で定義されたプロパティは、コンポーネントインスタンスを介して公開されます:
```

2021-04-24 10:21 UTC, naokie commented on src/guide/instance.md
> +このガイドでは `data` プロパティについて説明しました。 `data` で定義されたプロパティは、コンポーネントインスタンスを介して公開されます:
ありがとうございます！
Suggestion の内容で取り込みます

2021-04-24 10:23 UTC, naokie commented
レビューありがとうございました！
Suggestion してもらったもの取り込んで、修正反映済みです。

2021-04-24 15:43 UTC, kazupon approved these changes

2021-04-24 15:43 UTC, kazupon commented
ありがとうございます！
マージします！

2021-04-24 15:43 UTC, merged