Guide > Component Basics の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #281
Opened 2021-04-25 10:19 UTC by naokie

## Description of Problem

Guide > Component Basics の翻訳を master に追従しました。
https://v3.vuejs.org/guide/component-basics.html
https://github.com/vuejs/docs-next/blob/master/src/guide/component-basics.md

## Proposed Solution

ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/component-basics.md

前回からの差分
https://github.com/vuejs/docs-next/commit/8ee82a92207f1f8f33cc8466f3ca949825312805#diff-5fceb06c7c1b83dc62c300ff985d1949e672a74967b4c092b60185319e12d7fd
https://github.com/vuejs/docs-next/commit/e554cd6f15fb201d8dc9e03e0f07e4a80e776f19#diff-5fceb06c7c1b83dc62c300ff985d1949e672a74967b4c092b60185319e12d7fd
https://github.com/vuejs/docs-next/commit/0eebf0e5fa2a1436de4afdb8c345a1b0cb7d71ea#diff-5fceb06c7c1b83dc62c300ff985d1949e672a74967b4c092b60185319e12d7fd

## Additional Information

https://github.com/vuejs/docs-next/commit/2706494ebba1f70593b067e4a2bfcfd7dea90128#diff-5fceb06c7c1b83dc62c300ff985d1949e672a74967b4c092b60185319e12d7fd
#187 と #200 で適用済みです

2021-04-26 14:28 UTC, kazupon requested changes
レビューコメントしました。
確認お願いします！

2021-04-26 14:28 UTC, kazupon commented on src/guide/component-basics.md
> +プロパティ属性に値が渡されると、渡されたそのコンポーネントインスタンスのプロパティになります。
`The value of that property is accessible within the template, just like any other component property.` が抜けているようですので、お願いできますか？ 🙏

2021-04-27 12:08 UTC, naokie commented on src/guide/component-basics.md
> +プロパティ属性に値が渡されると、渡されたそのコンポーネントインスタンスのプロパティになります。
2文目が抜けてました！
ありがとうございます

2021-04-27 12:12 UTC, naokie commented
翻訳し忘れた1文追加しました。

2021-04-27 15:12 UTC, kazupon approved these changes

2021-04-27 15:13 UTC, merged