Guide > Composition API > Setup の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #283
Opened 2021-04-26 12:26 UTC by naokie

## Description of Problem

Guide > Composition API > Setup の翻訳を追従しました。
https://v3.vuejs.org/guide/composition-api-setup.html
https://github.com/vuejs/docs-next/blob/master/src/guide/composition-api-setup.md

## Proposed Solution

ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/composition-api-setup.md

前回からの差分
https://github.com/vuejs/docs-next/commit/c05b8e66bcf1e8c614e4569c43b20df5249b864f#diff-861c883c19deb5fffdbcbaf69ecc06bab99f7f21c623d3ea197fa227826b5c05
https://github.com/vuejs/docs-next/commit/b3a53a2919a3594fd9c15a87eb985f4f6eddb6b9#diff-861c883c19deb5fffdbcbaf69ecc06bab99f7f21c623d3ea197fa227826b5c05
https://github.com/vuejs/docs-next/commit/c84c5f304c37436ea0f50d2299593a61ecc652c2#diff-861c883c19deb5fffdbcbaf69ecc06bab99f7f21c623d3ea197fa227826b5c05
https://github.com/vuejs/docs-next/commit/a502ebe337998ec9d09460d5e56f981870c3039b#diff-861c883c19deb5fffdbcbaf69ecc06bab99f7f21c623d3ea197fa227826b5c05
https://github.com/vuejs/docs-next/commit/3e5e52e9fdd3abbaab19849dc0dd81752d216216#diff-861c883c19deb5fffdbcbaf69ecc06bab99f7f21c623d3ea197fa227826b5c05

## Additional Information

https://github.com/vuejs/docs-next/commit/8822df4a70981bfa49d42dfd5361ca3db1903fb1#diff-861c883c19deb5fffdbcbaf69ecc06bab99f7f21c623d3ea197fa227826b5c05
#196 でマージ済みでした。

#94 にしたがって、表記揺れを修正しました。

2021-04-26 14:42 UTC, kazupon requested changes
レビューしました。確認お願いします！

2021-04-26 14:42 UTC, kazupon commented on src/guide/composition-api-setup.md
> +## レンダリング関数での使用
`レンダリング関数` は、render という用語が一般的になってきたので、英語表記 `Render 関数` とにしておきたいです。

2021-04-26 14:42 UTC, kazupon commented on src/guide/composition-api-setup.md
> +`setup` は同じスコープで宣言されたリアクティブなステートを直接利用することができるレンダリング関数を返すこともできます:
ここのレンダリング関数も同じく `Render 関数` に。

2021-04-27 11:59 UTC, naokie commented on src/guide/composition-api-setup.md
> +## レンダリング関数での使用
他のフレームワークの話をするときも、一般化してきましたね。

https://v3.ja.vuejs.org/guide/render-function.html
ドキュメント全体としても、ここが用語のソースになるからこれで統一ですね。

2021-04-27 12:04 UTC, naokie commented
ドキュメント全体的に「Render 関数」で揃えておきました！

2021-04-27 15:11 UTC, kazupon approved these changes

2021-04-27 15:12 UTC, merged