Guide > Components In-Depth > Slots の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #293
Opened 2021-04-29 11:08 UTC by naokie

## Description of Problem

Guide > Components In-Depth > Slots の翻訳を追従しました。
https://v3.vuejs.org/guide/component-slots.html

## Proposed Solution

ファイル変更履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/component-slots.md

前回からの差分
https://github.com/vuejs/docs-next/commit/fc1449bdb1c30b4882cc7fc350bbf8b36e6a0a0e#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec
https://github.com/vuejs/docs-next/commit/b78e9780cc929322b62ae286355972cf38acafcc#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec
https://github.com/vuejs/docs-next/commit/b6070fe76b44a9872838494ba1e9dd957fe5c486#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec
https://github.com/vuejs/docs-next/commit/a2f811f6321a2fd3cacd5629c3136f7162586972#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec
https://github.com/vuejs/docs-next/commit/705fea0dc6eceb2c9a3f9e9bee3ca70d62acafe9#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec
https://github.com/vuejs/docs-next/commit/aefafd487fbc6579f0d67ea4cf2be29a00358338#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec
https://github.com/vuejs/docs-next/commit/4a333dd299ab82ed1965e2e8fda9dfab5dd70963#diff-35274a894b839664d9b049b61f4ceb59208a220f0008127c91fd80249d07a0ec

## Additional Information

2021-04-29 11:09 UTC, naokie commented on src/guide/component-slots.md
> +**`v-slot` は（[一つの例外](#デフォルトスロットしかない場合の省略記法) を除き） `<template>` にしか指定できないことに注意してください。
「デフォルトスロット」の「デ」に差分があってページ内リンクが動作してなかったため修正しました。

2021-04-29 14:30 UTC, kazupon requested changes
レビューしました。
確認お願いします！

2021-04-29 14:30 UTC, kazupon commented on src/guide/component-slots.md
> +親コンポーネントでこれをカスタマイズするために、<span v-pre>`{{ item }}`</span> を `<slot>` に置き換えたい場合があります:
原文ですが、
```
We might want to replace the {{ item }} with a <slot> to customize it on parent component:
```

となっていて、`<span v-pre>` と `</span>` はいらないと思います。

https://v3.vuejs.org/guide/component-slots.html#scoped-slots

2021-04-30 11:01 UTC, naokie commented on src/guide/component-slots.md
> +親コンポーネントでこれをカスタマイズするために、<span v-pre>`{{ item }}`</span> を `<slot>` に置き換えたい場合があります:
https://github.com/vuejs/docs-next/pull/799

ここで問題になっていた下図の現象、日本語訳でも起きちゃうんですよね。

![image](https://user-images.githubusercontent.com/30752/116685479-60203980-a9ed-11eb-876e-4b1b807d2950.png)

![image](https://user-images.githubusercontent.com/30752/116686307-98744780-a9ee-11eb-9908-43d2a6f6946d.png)

VuePress の hack のようなものなのですが、そのまま取り込もうと思います。

2021-04-30 11:05 UTC, naokie commented
レビューいただいた箇所、コメントお返ししたので再レビューお願いします。

2021-04-30 15:28 UTC, kazupon commented on src/guide/component-slots.md
> +親コンポーネントでこれをカスタマイズするために、<span v-pre>`{{ item }}`</span> を `<slot>` に置き換えたい場合があります:
なるほど...
了解しました！

2021-04-30 15:30 UTC, kazupon commented on src/guide/component-slots.md
> +親コンポーネントでこれをカスタマイズするために、<span v-pre>`{{ item }}`</span> を `<slot>` に置き換えたい場合があります:
原文と同じく、取り込みましょう！

2021-04-30 15:30 UTC, kazupon approved these changes

2021-04-30 15:30 UTC, merged