【WIP】Guide > Enter & Leave Transitions の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #307
Opened 2021-05-03 14:25 UTC by Katakuranatsumi

## Description of Problem
Guide >  Enter & Leave Transitions の翻訳を追従しました。
https://v3.vuejs.org/guide/transitions-enterleave.html

## Proposed Solution
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/transitions-enterleave.md

前回からの差分
https://github.com/vuejs/docs-next/commit/5d2a1e354fa23caa0972cef2833171dd384eff0f#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65
https://github.com/vuejs/docs-next/commit/40e361ff407dfb1b95c79a75d53a0d55810bf087#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65
https://github.com/vuejs/docs-next/commit/3f699dff18569229843691b8946057e7fe0f2ab9#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65

(https://github.com/vuejs/docs-next/commit/722b92ee0eb2e7f4ad64092481b6b70932b6209a#diff-bd22f27bea3e777dd5f5f0393cc3bca3482956bf9a395876b15aefd64cdcbf65 の差分は、すでに[Guide > Introduction の翻訳を追従](https://github.com/vuejs-jp/ja.vuejs.org/pull/272)で対応していただいていたため対応しておりませんmm)
## Additional Information
翻訳の追従の他にも、原文と行のずれがあった箇所を以下のように修正しています🙏
- 73行目〜83行目までの番号付きリストの間に、原文にならって空白の行を追加
- 295行目と315行目のコメントを、原文にならって2行にするよう修正

2021-05-03 15:49 UTC, naokie requested changes
```
@@ -189,7 +189,7 @@ Vue.createApp(Demo).mount('#demo')
     transform: scale(0);
   }
   50% {
-    transform: scale(1.5);
+    transform: scale(1.25);
   }
   100% {
     transform: scale(1);
```

この差分が抜けちゃってるかもしれないです。

2021-05-03 15:49 UTC, naokie commented on src/guide/transitions-enterleave.md
> +  <input v-model="view" type="radio" value="v-a" id="a"><label for="a">A</label>	TODO: update to Vue 3
```suggestion
  <input v-model="view" type="radio" value="v-a" id="a"><label for="a">A</label>
```

L506 で消したものが混入しちゃったかもしれませんね。

2021-05-03 15:49 UTC, naokie commented on src/guide/transitions-enterleave.md
> +このページでは、entering/leaving とリストのトランジションについてのみ取り扱いますが、次の章では、[リストのトランジション](transitions-list.html) と [状態のトランジション](transitions-state.html) について扱います。
```suggestion
このページでは、entering/leaving のトランジションについてのみ取り扱いますが、次の章では、[リストのトランジション](transitions-list.html) と [状態のトランジション](transitions-state.html) について扱います。
```

リストのトランジションは別ページにという説明に変わったんですね。

2021-05-04 01:57 UTC, Katakuranatsumi commented on src/guide/transitions-enterleave.md
> +  <input v-model="view" type="radio" value="v-a" id="a"><label for="a">A</label>	TODO: update to Vue 3
ご確認ありがとうございましたmm
失礼しました、 5b3da7c で削除しました🙇‍♀️

2021-05-04 01:59 UTC, Katakuranatsumi commented on src/guide/transitions-enterleave.md
> +このページでは、entering/leaving とリストのトランジションについてのみ取り扱いますが、次の章では、[リストのトランジション](transitions-list.html) と [状態のトランジション](transitions-state.html) について扱います。
「リストのトランジション」のままになっていました、失礼しました🙇‍♀️
88c405d で修正しましたmm

2021-05-04 02:01 UTC, Katakuranatsumi commented
5f8e6fe でL182が `transform: scale(1.25);` になるよう修正しましたmm

2021-05-04 04:57 UTC, naokie approved these changes
ありがとうございました 👍🏼 
LGTM!!

2021-05-04 04:58 UTC, merged