Guide > Reusability & Composition > Render functions の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #308
Opened 2021-05-04 12:36 UTC by naokie

## Description of Problem

Guide > Reusability & Composition > Render functions の翻訳を追従しました。
https://v3.vuejs.org/guide/render-function.html

## Proposed Solution

ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/render-function.md

前回からの差分
https://github.com/vuejs/docs-next/commit/706a8cdeb0a6ff5aea4b8d6d7ed1996c785274fd#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/9ae70db2aa1145b27bdd301729f79c6c1bb7ba1c#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/dbeed5b73a88d8c8852a52626e9e431fe47ea991#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/e554cd6f15fb201d8dc9e03e0f07e4a80e776f19#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/2915212b7e5d26ef797230a01aaee87b82bc0610#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/ac5bec37431e43f91c61db6089f4b48058d7961a#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/363641a13f600cb965ece3fd1c93210826f61a17#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/9e3d61a99e97a3c8448b001a71ea5cef97fdb7f9#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/7745e705222fc8c08bf81bfd61457ce218d8cd4f#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/eb244fdd35b7e45b5fd3ac0a06a9c5cb54abe4cd#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/588c1f6d072f7c0763355ffddde2f26a0ecfa095#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/1d2fb1696b540e94572046e0ecfcc23f22983581#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/da874b21fab5d00cd6edb876d69a841c0052ee69#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a
https://github.com/vuejs/docs-next/commit/5753b78caa80309065554b2c2583bcdce03bc325#diff-0b635f32793fe88d869035c17f5143d6a7011183741021e19963a52beb70927a

## Additional Information

2021-05-05 15:54 UTC, kazupon requested changes
レビューしました！
確認お願いします！

2021-05-05 15:54 UTC, kazupon commented on src/guide/render-function.md
> +舞台裏では、テンプレートは `resolveDynamicComponent` をつかって `is` 属性を実装しています。 `render` 関数で `is` 属性がもつ、すべての柔軟性が必要な場合は、同じ関数を使うことができます:
`Behind the scenes,` の訳ですが、ここでは、`裏では` の方がドキュメントの文調的に違和感ないと思います。

2021-05-06 11:12 UTC, naokie commented on src/guide/render-function.md
> +舞台裏では、テンプレートは `resolveDynamicComponent` をつかって `is` 属性を実装しています。 `render` 関数で `is` 属性がもつ、すべての柔軟性が必要な場合は、同じ関数を使うことができます:
そうですね。ここは直訳するか、悩みどころでした。
ありがとうございます！

2021-05-06 11:15 UTC, naokie commented
レビューありがとうございました！
`Behind the scene` は修正しました。

2021-05-06 14:30 UTC, kazupon approved these changes

2021-05-06 14:30 UTC, merged