Guide > Tooling > Single File Components の翻訳を追従
vuejs-jp/ja.vuejs.org pull request #309
Opened 2021-05-04 12:38 UTC by naokie

## Description of Problem

Guide > Tooling > Single File Components の翻訳を追従しました。
https://v3.vuejs.org/guide/single-file-component.html

## Proposed Solution

ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/single-file-component.md

前回からの差分
https://github.com/vuejs/docs-next/commit/8c8d85aaab77ae174cdbbc14c0c3a57aadf51598#diff-7d4d6d18bce98fb202b53d0597ea1e4a7ba7f467b9db5a86e4c25d8d59fc7fe0
https://github.com/vuejs/docs-next/commit/d451d21a2177556a0adedcc0005b853905a477b6#diff-7d4d6d18bce98fb202b53d0597ea1e4a7ba7f467b9db5a86e4c25d8d59fc7fe0
https://github.com/vuejs/docs-next/commit/2aa4491eb73b1b207292539e7f7615c8d46a587b#diff-7d4d6d18bce98fb202b53d0597ea1e4a7ba7f467b9db5a86e4c25d8d59fc7fe0
https://github.com/vuejs/docs-next/commit/9436d6c66347842c413af661d6e6d4cddec18905#diff-7d4d6d18bce98fb202b53d0597ea1e4a7ba7f467b9db5a86e4c25d8d59fc7fe0
https://github.com/vuejs/docs-next/commit/5753b78caa80309065554b2c2583bcdce03bc325#diff-7d4d6d18bce98fb202b53d0597ea1e4a7ba7f467b9db5a86e4c25d8d59fc7fe0

## Additional Information

2021-05-05 16:02 UTC, kazupon requested changes
レビューしました。確認お願いします！

2021-05-05 16:02 UTC, kazupon commented on src/guide/single-file-component.md
> +ここで指定しています:
`Here we are specifying:` の訳ですが、原文には目的となる word がないですが、それを踏まえて以下のように訳しておくといいかと思います。
```suggestion
ここでは、以下の内容を指定しています:
```

2021-05-06 11:18 UTC, naokie commented on src/guide/single-file-component.md
> +ここで指定しています:
そうですね。ここは他と比べて珍しく、指示語とかなかったので読みやすくすべきでした。

2021-05-06 11:19 UTC, naokie commented
Suggestion ありがとうございました。
訳しながら、どうしようか迷っていたポイントをピンポイントで指摘されちゃいましたね 😅

2021-05-06 14:31 UTC, merged