Guide > Server-Side Rendering Guide > Introduction の翻訳
vuejs-jp/ja.vuejs.org pull request #321
Opened 2021-05-12 12:19 UTC by naokie

## Description of Problem

Guide > Server-Side Rendering Guide > Introduction の翻訳しました。
https://v3.vuejs.org/guide/ssr/introduction.html

## Proposed Solution

## Additional Information

2021-05-13 14:48 UTC, kazupon requested changes
レビューしました。確認お願いしいます！

2021-05-13 14:48 UTC, kazupon commented on src/guide/ssr/introduction.md
> +> このガイドは現在開発中です
`development` 、愚直に訳すと確かに `開発` なのですが、ドキュメントの文脈だとちょっと違和感がありますね。
意訳気味に、`執筆調整中`とかどうでしょう？

2021-05-13 14:48 UTC, kazupon commented on src/guide/ssr/introduction.md
> +Vue.js はクライアントサイドのアプリケーションを構築するためのフレームワークです。デフォルトでは、 Vue コンポーネントは出力としてブラウザ内で DOM の生成と操作をします。しかしサーバから、同じコンポーネントを HTML 文字列にレンダリングして、それらをブラウザに直接送信して、最終的にはクライアント上での静的なマークアップを完全にインタラクティブなアプリケーションに「Hydrate
`Hydrate` は括弧付で読み方も書いておいたほうが use friendry になると思うので、以下でどうでしょう？
```suggestion
Vue.js はクライアントサイドのアプリケーションを構築するためのフレームワークです。デフォルトでは、 Vue コンポーネントは出力としてブラウザ内で DOM の生成と操作をします。しかしサーバから、同じコンポーネントを HTML 文字列にレンダリングして、それらをブラウザに直接送信して、最終的にはクライアント上での静的なマークアップを完全にインタラクティブなアプリケーションに「Hydrate（ハイドレート）」することも可能です。
```

2021-05-13 14:48 UTC, kazupon commented on src/guide/ssr/introduction.md
> +サーバサイドレンダリングした Vue.js アプリケーションは、 「Isomorphic」とか「Universal」と考えることもできます。これはつまり、アプリケーションのコードの大部分がサーバ **と** クライアントの両方で実行されるということを意味します。
ここの `Isomorphic` と  `Universal` の用語も以下のような感じでどうでしょう？
```suggestion
サーバサイドレンダリングした Vue.js アプリケーションは、 「Isomorphic（アイソモルフィック）」とか「Universal（ユニバーサル）」と考えることもできます。これはつまり、アプリケーションのコードの大部分がサーバ **と** クライアントの両方で実行されるということを意味します。
```

2021-05-15 04:01 UTC, naokie commented on src/guide/ssr/introduction.md
> +> このガイドは現在開発中です
いいですね。しっくりするので、いただきます！

2021-05-15 13:10 UTC, naokie commented
Suggestion 助かります！
レビューすべて反映しました。

2021-05-15 13:16 UTC, kazupon approved these changes

2021-05-15 13:16 UTC, kazupon commented
ありがとうございます！マージします！

2021-05-15 13:16 UTC, merged