Guide > Server-Side Rendering Guide > Getting Started の翻訳
vuejs-jp/ja.vuejs.org pull request #322
Opened 2021-05-12 12:19 UTC by naokie

## Description of Problem

Guide > Server-Side Rendering Guide > Getting Started の翻訳
https://v3.vuejs.org/guide/ssr/getting-started.html

## Proposed Solution

## Additional Information

2021-05-13 14:52 UTC, kazupon requested changes
レビューしました！確認お願いします！

2021-05-13 14:52 UTC, kazupon commented on src/guide/ssr/getting-started.md
> +> このガイドは現在開発中です
このコメントと同じく。
https://github.com/vuejs-jp/ja.vuejs.org/pull/321#discussion_r631862835

2021-05-13 14:52 UTC, kazupon commented on src/guide/ssr/getting-started.md
> +- Node.js のバージョンは 10 以上を推奨します。
Node v10 はつい最近サポートされなくなったので、本家に PR 送るチャンスかも。
https://nodejs.org/ja/about/releases/

2021-05-15 05:26 UTC, naokie commented on src/guide/ssr/getting-started.md
> +- Node.js のバージョンは 10 以上を推奨します。
さっそく送っておきました 👍🏼

2021-05-15 13:09 UTC, naokie commented
レビューありがとうございました！すべて反映済みです。
原文への　PR　もｗ

2021-05-16 09:03 UTC, merged