Migration Guide > Migration Build の翻訳
vuejs-jp/ja.vuejs.org pull request #398
Opened 2021-06-15 03:14 UTC by t0yohei

## Description of Problem

Migration Guide > Migration Build の翻訳を追加します。

resolve #379

ref: https://github.com/vuejs/docs-next/pull/1033

## Proposed Solution

## Additional Information

2021-06-16 07:41 UTC, naokie commented on src/guide/migration/global-api.md
> +// コンストラクタの作成
```suggestion

// コンストラクタの作成
```

原文との対応行を一致させたいため、空行を1つお願いします。

2021-06-16 07:42 UTC, naokie commented on src/guide/migration/global-api.md
> +Vue.createApp(Profile).mount('#mount-point')
```suggestion

Vue.createApp(Profile).mount('#mount-point')
```

同上の理由で空行を1つお願いします。

2021-06-16 07:59 UTC, naokie commented on src/guide/migration/migration-build.md
> +- Vue 2 の内部 API または文書化されていない動作に頼った依存関係。最も一般的なケースは、 `VNodes` プライベートプロパティの使用です。[Vuetify](https://vuetifyjs.com/en/)、[Quasar](https://quasar.dev/)、[ElementUI](https://element.eleme.io/#/en-US)などのコンポーネント
```suggestion
- Vue 2 の内部 API またはドキュメント化されていない動作に頼った依存関係。最も一般的なケースは、 `VNodes` プライベートプロパティの使用です。[Vuetify](https://vuetifyjs.com/en/)、[Quasar](https://quasar.dev/)、[ElementUI](https://element.eleme.io/#/en-US)などのコンポーネントライブラリに依存している場合は、Vue 3 と互換性のあるバージョンを待つことをお勧めします。
```

`documented` は「ドキュメント化」に和訳を寄せていっているので、合わせてもらえると助かります。

2021-06-16 08:03 UTC, naokie commented on src/guide/migration/migration-build.md
> +- Internet Explorer 11 のサポート。[Vue 3 は公式に IE11 サポートの計画を中止しました](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0038-vue3-ie11-support.md)。まだ IE11 以下をサポートする必要がある場合は、Vue 2 のままにしておく必要があります。
```suggestion
- Internet Explorer 11 のサポート: [Vue 3 は公式に IE11 サポートの計画を中止しました](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0038-vue3-ie11-support.md)。まだ IE11 以下をサポートする必要がある場合は、Vue 2 のままにしておく必要があります。
```

原文の `:` を尊重するようにガイドラインを設けていますので、残してもらえますか。

See also.
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/.github/CONTRIBUTING.md

2021-06-16 08:04 UTC, naokie commented on src/guide/migration/migration-build.md
> +- サーバーサイドレンダリング。移行ビルドは SSR にも使用できますが、カスタム SSR セットアップの移行はもっと複雑です。一般的な対処法は、`vue-server-renderer` を[`@vue/server-renderer`](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)に置き換えるこ
```suggestion
- サーバーサイドレンダリング: 移行ビルドは SSR にも使用できますが、カスタム SSR セットアップの移行はもっと複雑です。一般的な対処法は、`vue-server-renderer` を[`@vue/server-renderer`](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)に置き換えることです。Vue 3 ではバンドルレンダラが提供されなくなったため、Vue 3 の SSR を[Vite](https://vitejs.dev/guide/ssr.html)で使用することが推奨されています。また、[Nuxt.js](https://nuxtjs.org/)を使用している場合は、Nuxt 3 を待ったほうがよいでしょう。
```

同上の理由でお願いします。

2021-06-16 08:19 UTC, naokie commented on src/guide/migration/migration-build.md
> +今回の移行ビルドでは、公開されている Vue 2 の API と動作のみをカバーすることを目的としていることに注意してください。文書化されていない動作に依存しているために移行ビルドでアプリケーションが動作しなかったとしても、そのようなケースへの対応として移行ビルドを調整する可能性は低いでしょう。問題となっている動作への依存を排除するためのリファクタリングを検討してください。
```suggestion
今回の移行ビルドでは、公開されている Vue 2 の API と動作のみをカバーすることを目的としていることに注意してください。ドキュメント化されていない動作に依存しているために移行ビルドでアプリケーションが動作しなかったとしても、そのようなケースへの対応として移行ビルドを調整する可能性は低いでしょう。問題となっている動作への依存を排除するためのリファクタリングを検討してください。
```

2021-06-16 08:21 UTC, naokie commented on src/guide/migration/migration-build.md
> +### 準備編
```suggestion
### 準備
```

同レベルの見出し「インストール」を「インストール編」としないならば、文体を合わせるために削除お願いします。

2021-06-16 08:22 UTC, naokie commented on src/guide/migration/migration-build.md
> +   - カスタム webpack セットアップを使用している場合。`vue-loader` を `^16.0.0` にアップグレードします。
```suggestion
   - カスタム webpack セットアップを使用している場合: `vue-loader` を `^16.0.0` にアップグレードします。
```

同上の理由でお願いします。

2021-06-16 08:23 UTC, naokie commented on src/guide/migration/migration-build.md
> +   - (代替手段) [Vite](https://vitejs.dev/) + [veite-plugin-vue2](https://github.com/underfin/vite-plugin-vue2)に移行します。[[コミット例](https://github.com/vuejs/vue-hackernews-2.0/commit/565b948919eb58f22a32afca7
```suggestion
   - (代替手段) [Vite](https://vitejs.dev/) + [vite-plugin-vue2](https://github.com/underfin/vite-plugin-vue2)に移行します。[[コミット例](https://github.com/vuejs/vue-hackernews-2.0/commit/565b948919eb58f22a32afca7e321b490cb3b074)]
```

2021-06-17 10:21 UTC, naokie commented on src/guide/migration/migration-build.md
> +   アップグレード後、`<router-view>` で `<transition>` や `<keep-alive>` を使用するには、新しい [scoped-slot ベースのシンタックス](https://next.router.vuejs.org/guide/migration/index.html#router-view-keep-alive-and-transition) を使用す
```suggestion
   アップグレード後、`<router-view>` で `<transition>` や `<keep-alive>` を使用するには、新しい [scoped-slot ベースの構文](https://next.router.vuejs.org/guide/migration/index.html#router-view-keep-alive-and-transition) を使用する必要があります。
```

「syntax -> 構文」で用語統一しているので、お願いします。

2021-06-17 10:32 UTC, naokie commented on src/guide/migration/migration-build.md
> +10. 個々の警告を狙い撃ちします。一部の機能は、Vue 2 と Vue 3 の間で矛盾した動作をすることに注意してください。例えば、レンダリング関数 API や、関数コンポーネントと非同期コンポーネントの変更などがあります。アプリケーションの他の部分に影響を与えずに Vue 3 の API に移行するには、[`compatConfig` オプション](#コンポーネントごとの設定)を使用して
```suggestion
10. 個々の警告を取り除きます。一部の機能は、Vue 2 と Vue 3 の間で矛盾した動作をすることに注意してください。例えば、Render 関数 API や、関数型コンポーネントと非同期コンポーネントの変更などがあります。アプリケーションの他の部分に影響を与えずに Vue 3 の API に移行するには、[`compatConfig` オプション](#コンポーネントごとの設定)を使用して、コンポーネントごとに Vue 3 の動作をオプトインすることができます。
```

辞書的に直接だと「狙い撃つ」もあるのですが、ここでは警告をピックアップして取り除くという、やさしい言葉で良いと思います。

https://v3.ja.vuejs.org/guide/migration/render-function-api.html#%E6%A6%82%E8%A6%81
the render function api には、移行ガイドに訳文があるため、統一お願いします。

https://v3.ja.vuejs.org/guide/migration/functional-components.html
functional component にも、移行ガイドに訳文があるため、統一をお願いします。

2021-06-17 10:32 UTC, naokie commented on src/guide/migration/migration-build.md
> +compat の機能は個別に無効にすることができます。
```suggestion
compat の機能は個別に無効にすることができます:
```

同上の理由でお願いします。

2021-06-17 10:32 UTC, naokie commented on src/guide/migration/migration-build.md
> +また、アプリケーション全体をデフォルトで Vue 3 の動作にして、特定の compat 機能だけを有効にすることもできます。
```suggestion
また、アプリケーション全体をデフォルトで Vue 3 の動作にして、特定の compat 機能だけを有効にすることもできます:
```

2021-06-17 10:34 UTC, naokie commented on src/guide/migration/migration-build.md
> +// すべてを Vue 3 の動作にデフォルトし、特定の機能のみ compat を有効にする
```suggestion
// すべてを Vue 3 の動作にデフォルトし、
// 特定の機能のみ compat を有効にする
```

原文と行を一致させるために、改行をお願いします。

2021-06-17 10:35 UTC, naokie commented on src/guide/migration/migration-build.md
> +コンポーネントは `compatConfig` オプションを使用することができます。このオプションには、グローバルの `configureCompat` メソッドと同じオプションが指定できます。
```suggestion
コンポーネントは `compatConfig` オプションを使用することができます。このオプションには、グローバルの `configureCompat` メソッドと同じオプションが指定できます:
```

2021-06-17 10:37 UTC, kazupon approved these changes
内容確認 👀 しました。
翻訳内容自体はほぼ問題ありません！
本当にありがとうございます！

naokieさんに指摘された部分の修正お願いします！

2021-06-17 10:41 UTC, naokie commented on src/guide/migration/migration-build.md
> +`COMPILER_` で始まる機能は、コンパイラ固有のものです。フルビルド(ブラウザ内コンパイラ付き)を使用している場合は、実行時に設定することができます。しかし、ビルドセットアップを使用している場合は、代わりにビルドコンフィグの `compilerOptions` で設定する必要があります(上記のコンフィグ例を参照)。
```suggestion
`COMPILER_` で始まる機能は、コンパイラ固有のものです。完全なビルド(ブラウザ内コンパイラ付き)を使用している場合は、実行時に設定することができます。しかし、ビルドセットアップを使用している場合は、代わりにビルドコンフィグの `compilerOptions` で設定する必要があります(上記のコンフィグ例を参照)。
```

https://v3.ja.vuejs.org/guide/installation.html#cdn-%E3%82%92%E5%88%A9%E7%94%A8%E3%80%81%E3%81%BE%E3%81%9F%E3%81%AF%E3%83%8F%E3%82%99%E3%83%B3%E3%83%88%E3%82%99%E3%83%A9%E3%83%BC%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88

full build には、エッセンシャルガイドに訳文があるため、統一お願いします。

2021-06-17 10:45 UTC, naokie commented on src/guide/migration/migration-build.md
> +| INSTANCE_EVENT_EMITTER       | ✔    | `vm.$on`, `vm.$off`, `vm.$once` は削除されました                                                       | [link](/guide/migration/events-api.html)
```suggestion
| INSTANCE_EVENT_EMITTER       | ✔    | `vm.$on`、`vm.$off`、`vm.$once` は削除されました                                                       | [link](/guide/migration/events-api.html)                                                   |
```

2021-06-17 10:49 UTC, naokie commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 関数コンポーネントの API が変更されました(プレーンな関数であることが必須になりました)                  | [link](/guide/migration/functional-components.html)                                        |
```suggestion
| COMPONENT_FUNCTIONAL         | ✔    | 関数型コンポーネントの API が変更されました(プレーンな関数であることが必須になりました)                  | [link](/guide/migration/functional-components.html)                                        |
```

2021-06-17 10:49 UTC, naokie commented on src/guide/migration/migration-build.md
> +| RENDER_FUNCTION              | ✔    | レンダリング関数の API が変更されました                                                                | [link](/guide/migration/render-function-api.html)
```suggestion
| RENDER_FUNCTION              | ✔    | Render 関数の API が変更されました                                                                | [link](/guide/migration/render-function-api.html)                                          |
```

2021-06-17 10:50 UTC, naokie commented on src/guide/migration/migration-build.md
> +| FILTERS                      | ✔    | Filters は削除されました(このオプションは、ランタイムのフィルタ API にのみ影響します)                  | [link](/guide/migration/filters.html)
```suggestion
| FILTERS                      | ✔    | フィルタは削除されました(このオプションは、ランタイムのフィルタ API にのみ影響します)                  | [link](/guide/migration/filters.html)                                                      |
```

2021-06-17 10:53 UTC, naokie commented on src/guide/migration/migration-build.md
> +| ATTR_ENUMERATED_COERSION     | ✔    | 特殊なケースの列挙型属性は廃止されました                                                               | [link](/guide/migration/attribute-coercion.html)
```suggestion
| ATTR_ENUMERATED_COERSION     | ✔    | 特殊なケースの列挙された属性は廃止されました                                                               | [link](/guide/migration/attribute-coercion.html)                                           |
```

https://v3.ja.vuejs.org/guide/migration/attribute-coercion.html

2021-06-17 10:59 UTC, naokie commented on src/guide/migration/migration-build.md
> +| COMPILER_V_BIND_OBJECT_ORDER | ✔    | `v-bind="object"` はオーダーセンシティブになりました                                                   | [link](/guide/migration/v-bind.html)
```suggestion
| COMPILER_V_BIND_OBJECT_ORDER | ✔    | `v-bind="object"` は順番に注意が必要になりました                                                   | [link](/guide/migration/v-bind.html)                                                       |
```

https://v3.ja.vuejs.org/guide/migration/v-bind.html
和訳できるものなので、変更してみました。

2021-06-17 11:03 UTC, naokie requested changes
@t0yohei 
翻訳ありがとうございました！
ドキュメント全体のガイドラインや、単語の統一から、構成入れさせてもらいました。
よろしくお願いします！

2021-06-17 11:22 UTC, t0yohei commented
@kazupon @naokie 
翻訳のレビューありがとうございました！
レビューいただいた点、修正いたしました。

2021-06-18 03:39 UTC, naokie approved these changes
LGTM です！
ありがとうございます

2021-06-18 03:40 UTC, merged