docs: add installation notes about compiler-sfc and bundlers
vuejs-jp/ja.vuejs.org pull request #408
Opened 2021-06-19 03:45 UTC by naokie

## Description of Problem

下記コミットの差分を追従します。

https://github.com/vuejs/docs/commit/6672db16d29fcc16bc40a6a1621928966b831cae

## Proposed Solution

## Additional Information

close #372

2021-06-26 14:11 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2021-06-26 14:11 UTC, kazupon commented on src/guide/installation.md
> +Vue は [単一ファイルコンポーネント](../guide/single-file-component.html)（SFCs）を作成するための、付随するツールも提供しています。SFCs を使いたい場合は、`@vue/compiler-sfc` もインストールする必要があります:
ここの `SFCs` は以下のように単一ファイルコンポーネントで訳しておいたいいですね。

```suggestion
Vue は [単一ファイルコンポーネント](../guide/single-file-component.html)（SFCs）を作成するための、付随するツールも提供しています。単一ファイルコンポーネントを使いたい場合は、`@vue/compiler-sfc` もインストールする必要があります:
```

2021-06-26 14:11 UTC, kazupon commented on src/guide/installation.md
> +また、`@vue/compiler-sfc` に加えて、選択したバンドラに適した SFC ローダーやプラグインも必要です。詳しくは [SFC ドキュメント](../guide/single-file-component.html) を参照してください。
ここも以下のように訳しておいてもいいです。
```suggestion
また、`@vue/compiler-sfc` に加えて、選択したバンドラに適した単一ファイルコンポーネントローダーやプラグインも必要です。詳しくは [単一ファイルコンポーネントドキュメント](../guide/single-file-component.html) を参照してください。
```

以下は独り言:

原文の `SFC loader` っていう用語、要は `vue-loader` や `rollup-plugin-vue` のようなバンドラで SFC をコンパイルするもののことを指しているのは分かるんですが、ちょっと違和感が。 🤔

2021-06-27 03:24 UTC, naokie commented on src/guide/installation.md
> +Vue は [単一ファイルコンポーネント](../guide/single-file-component.html)（SFCs）を作成するための、付随するツールも提供しています。SFCs を使いたい場合は、`@vue/compiler-sfc` もインストールする必要があります:
そうですね
先に「単一ファイルコンポーネント（SFCs）」としているので、そっちが正しかったです

2021-06-27 03:34 UTC, naokie commented on src/guide/installation.md
> +また、`@vue/compiler-sfc` に加えて、選択したバンドラに適した SFC ローダーやプラグインも必要です。詳しくは [SFC ドキュメント](../guide/single-file-component.html) を参照してください。
割と loaders というと webpack 固有の呼び方で `vue-loader` を指しますよね。
`@vue/compiler-sfc` はコンパイルするコア機能のみで、バンドラごとにブリッジしてくれるものが必要というニュアンスでしょうか。
ちょっと違和感はわかります。

2021-06-27 03:35 UTC, naokie commented
レビューありがとうございました！
修正完了です

2021-06-27 08:36 UTC, kazupon approved these changes

2021-06-27 08:36 UTC, merged