docs: add transition as root to the migration guide
vuejs-jp/ja.vuejs.org pull request #409
Opened 2021-06-19 04:19 UTC by naokie

## Description of Problem

下記コミットの差分を追従します。

https://github.com/vuejs/docs/commit/514943e7e67e692389b1ae9f45439a1242925dde

## Proposed Solution

## Additional Information

close #362

2021-06-26 14:13 UTC, kazupon commented on src/guide/migration/transition-as-root.md
> +# ルートしてのトランジション <MigrationBadges :badges="$frontmatter.badges" />
多分タイポだと思うんですが、`as` は `〜として` ですね。

```suggestion
# ルートとしてのトランジション <MigrationBadges :badges="$frontmatter.badges" />
```

2021-06-26 14:16 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします。

2021-06-27 03:23 UTC, naokie commented
またタイピングミス！見つけていただいて、ありがとうございます
修正しました

2021-06-27 08:35 UTC, kazupon approved these changes

2021-06-27 08:35 UTC, merged