API Reference > Options > Assets / Composition の翻訳
vuejs-jp/ja.vuejs.org pull request #443
Opened 2021-07-10 02:04 UTC by naokie

## Description of Problem

API Reference > Options の Assets と Composition の翻訳を追加しました。

https://v3.vuejs.org/api/options-assets.html
https://v3.vuejs.org/api/options-composition.html

## Proposed Solution

## Additional Information

2021-07-11 17:43 UTC, kazupon commented on src/api/options-assets.md
> +  そのコンポーネントインスタンスで利用可能なディレクティブのハッシュです。
このセクションで、度々 `the component` とでてくると思うんですが、`the` は特に `その` と訳さなくていいですね。
暗黙的にコンポーネント上で使用するときの状況のコンポーネントであると意識できるので。もし訳したとしても、`その` ではなく、`対象となるコンポーネント` とか `the` の訳以上の説明が必要だと思います。

2021-07-11 17:44 UTC, kazupon commented on src/api/options-assets.md
> +  そのコンポーネントインスタンスで利用可能なディレクティブのハッシュです。
毎回 `the` の訳を詳細に説明してもいいかと思うんですが、意訳的な訳が含んでしまうので、メンテナンスが大変というのもあります。

2021-07-11 17:49 UTC, kazupon requested changes
大変おまたせしました！
レビュー 👀 コメント 💬 したので、確認お願いします！

2021-07-17 03:39 UTC, naokie commented on src/api/options-assets.md
> +  そのコンポーネントインスタンスで利用可能なディレクティブのハッシュです。
レビューありがとうございます！
量の少ないページだったので機械的にやってしまってました 😓 

いつも `the` はなにを指しているんだろう？と訳文考えるときに思いますが、
こういった暗黙の文脈があるケースでは、省略したほうが日本語として読みやすいですよね。

2021-07-17 03:40 UTC, naokie commented
@kazupon 
毎度レビューありがとうございます。
指摘してもらった点、修正 DONE です！

2021-07-17 15:21 UTC, kazupon approved these changes

2021-07-17 15:21 UTC, merged