API Reference > Options > Lifecycle Hooks の翻訳
vuejs-jp/ja.vuejs.org pull request #460
Opened 2021-07-26 12:13 UTC by naokie

## Description of Problem

API Reference > Options > Lifecycle Hooks の翻訳を追加しました。

原文ページ:
https://v3.vuejs.org/api/options-lifecycle-hooks.html

## Proposed Solution

## Additional Information

2021-07-28 15:38 UTC, kazupon requested changes
大変遅くなりました。
レビュー 👀 コメント 💬 しました。
確認お願いします！

2021-07-28 15:38 UTC, kazupon commented on src/api/options-lifecycle-hooks.md
> +  データが変更されるとき、DOM が適用される前に呼び出されます。これは例えば、手動で追加されたイベントリスナを削除するといった、更新前に既存の DOM にアクセスするのに適しています。
`before the DOM is patched`  の `patched` は ここでは Virtual DOM の patch のプロセスのこと意味しているんですが、そのまま`適用`と訳すと何を適用するのかわからないので、以下な感じで少し意訳気味に訳しておくとよさそうです。
```suggestion
  データが変更されるとき、DOM に patch (Virtual DOM の処理プロセス)される前に呼び出されます。これは例えば、手動で追加されたイベントリスナを削除するといった、更新前に既存の DOM にアクセスするのに適しています。
```

2021-07-28 15:38 UTC, kazupon commented on src/api/options-lifecycle-hooks.md
> +  データの変更後に仮想 DOM が再レンダリングされ、適用された後に呼び出されます。
ここの `patched` も先でコメントしたところと同じく virtual dom の patch のことを意味していますね。
```suggestion
  データの変更後に仮想 DOM が再レンダリングされ、patch が適用された後に呼び出されます。
```

2021-07-28 15:38 UTC, kazupon commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
`kept-alive` コンポーネントというのはないですね。これ原文も`keep-alive` コンポーネントと間違っているので、原文も治す必要がありそうです。

2021-07-28 15:38 UTC, kazupon commented on src/api/options-lifecycle-hooks.md
> -  Called when a kept-alive component is deactivated.
ここの`kept-alive` コンポーネントも同様に原文も間違っています。

2021-07-31 04:31 UTC, naokie commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
https://v3.vuejs.org/api/built-in-components.html#keep-alive
この組み込みコンポーネントのことを指していると思うのですが、やっぱり間違いでしょうか？

2021-07-31 04:49 UTC, naokie commented on src/api/options-lifecycle-hooks.md
> +  データが変更されるとき、DOM が適用される前に呼び出されます。これは例えば、手動で追加されたイベントリスナを削除するといった、更新前に既存の DOM にアクセスするのに適しています。
なるほど runtime-dom を読んでみて、はじめてそういった処理に patchXXX と名前ついているの知りました。

2021-08-01 06:47 UTC, kazupon commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
はい、その `keep-alive` コンポーネントを指しています。
`kept-alive` は恐らく原文も typo しているので PR チャンスです！

2021-08-01 07:40 UTC, naokie commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
あ、typoでしたかw
全然気づかなかったです

2021-08-04 17:08 UTC, naokie commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
https://github.com/vuejs/docs/pull/1158
PR 出しておきました。

2021-08-10 12:40 UTC, naokie commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
これは意図的なものだとリプライもらいました。
ソースコードには出てくることなく、テストコードとかを読むとコメントで見つかりますね。

> kept-alive コンポーネント（keep-alive の子コンポーネント）がアクティブになったときに呼び出されます。

skirtles-code にリプライもらったとおり、それを説明的にしてこういった訳でどうでしょうか？

2021-08-10 15:59 UTC, kazupon commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
なるほど。自分もコード読んで理解しました。
https://github.com/vuejs/vue-next/blob/d045055b475f76624830ed594dd138ac71eccd4e/packages/runtime-core/src/components/KeepAlive.ts#L68

內部で子コンポーネントとして持っていますね。

>kept-alive コンポーネント（keep-alive の子コンポーネント）がアクティブになったときに呼び出されます。

もう少し、補足して以下でどうでしょう？

>kept-alive コンポーネント（keep-alive が內部で保持する子コンポーネント）がアクティブになったときに呼び出されます。

2021-08-14 08:56 UTC, naokie commented on src/api/options-lifecycle-hooks.md
> +  kept-alive コンポーネントがアクティブになったときに呼び出されます。
これに関する詳細についてドキュメントからは探せないので、より説明的になってよいですね！

2021-08-14 09:01 UTC, naokie commented
kept-alive コンポーネントについて修正したので、再レビューお願いします 🙏🏼

2021-08-14 09:36 UTC, kazupon approved these changes

2021-08-14 09:36 UTC, kazupon commented
LGTM!

2021-08-14 09:36 UTC, merged