Tooling > TypeScript Support
vuejs-jp/ja.vuejs.org pull request #53
Opened 2020-09-16 20:13 UTC by NozomuIkuta

resolves #41

2020-09-19 16:43 UTC, kazupon requested changes
レビュー 👀 してコメント 💬 しました。
確認お願いします！ 🙏

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +TypeScript による Vue アプリケーションの開発のために、すぐに利用できる TypeScript サポートを提供している [Visual Studio Code](https://code.visualstudio.com/) を強く推奨します。[シングルファイルコンポーネント](./single-file-components.html) (SFCs) を使用している場合、SFC
`シングルファイルコンポーネント` は `単一ファイルコンポーネント` でお願いします。 現時点で日本語公式ドキュメントはそのように訳して統一しているので。

あと、`awesome` の訳は(多分typo?) `素晴らしい` にしておきました。

```suggestion
TypeScript による Vue アプリケーションの開発のために、すぐに利用できる TypeScript サポートを提供している [Visual Studio Code](https://code.visualstudio.com/) を強く推奨します。[単一ファイルコンポーネント](./single-file-components.html) (SFCs) を使用している場合、SFC 内部での TypeScript の推論やその他の優れた機能を提供している、素晴らしい [Vetur エクステンション](https://github.com/vuejs/vetur) を入手してください。
```

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +複雑な型や推論の場合、[タイプアサーション](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) を使用してキャストすることができます:
技術用語は、カタカナ日本語で訳す場合は、以下のように原文の技術用語の載せてください！ 🙏 
(載せておくことで技術用語が翻訳されて意味が分からない人のためにも、原文を残して置くことによって理解できるようにしておくためです。)

```suggestion
複雑な型や推論の場合、[タイプアサーション (type assertions)](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) を使用してキャストすることができます:
```

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +## コンポジション API とともに使用する
@potato4d 
翻訳方針として v2 のときのガイドラインに従う形なんですが、`Compostion API`という技術用語、カタカナ日本語でとりあえず、訳す方向にします？

個人的にはカタカナ日本語に訳すのは、あまり意味がない(読み方が分かる程度)のと、訳してかえってわかりにくくなるとという過去の経験から、今後としては技術用語は、原文のままとしておきたいです。

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +### プロパティにアノテーションをつける
ここは、`プロパティ` に訳さず、 `Props` のままとしてください。 🙏 
`Props` としておくことで、Vue コンポーネントの props というのが読み手の分かりやすいので。

```suggestion
### Props にアノテーションをつける
```

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +    const filtered = props.message.filter(p => p.value) // エラーが起こります: 'filter' プロパティは文字列 (string) 型には存在しません。
`Property 'filter' does not exist on type 'string'` は TypeScript のコンパイラのエラーだと思うので、もしそうならば、訳さずそのままにしておきたいです。

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +    const result = year.value.split('') // => 'split' プロパティは 'number' 型に存在しません
ここの、`Property 'split' does not exist on type 'number'` も同じく、TypeScript のコンパイラのエラーだと思うので、もしそうならば、訳さずそのままにしておきたいです。

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +    const result = doubleCount.value.split('') // => 'split' プロパティは 'number' 型に存在しません。
`Property 'split' does not exist on type 'number'` も同じく、TypeScript のコンパイラのエラーだと思うので、もしそうならば、訳さずそのままにしておきたいです。

2020-09-19 16:43 UTC, kazupon commented on src/guide/typescript-support.md
> +    // リードオンリー
訳すならば、以下のような感じですね。 

```suggestion
    // 読み取り専用
```

2020-09-20 12:15 UTC, NozomuIkuta reviewed
@kazupon 

レビューありがとうございます！
ご指摘の部分は、「Composition API」の部分を除いて修正されたと思います。

2020-09-20 12:15 UTC, NozomuIkuta commented on src/guide/typescript-support.md
> +複雑な型や推論の場合、[タイプアサーション (type assertion)](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) を使用してキャストすることができます:
こちら、原文の通り「type assertion」（単数形）を併記しました。

2020-09-20 12:15 UTC, NozomuIkuta commented on src/guide/typescript-support.md
> +    const filtered = props.message.filter(p => p.value) // エラーが起こります: Property 'filter' does not exist on type 'string'
こちら、TypeScriptのエラーメッセージのようですので、原文に戻しました。

2020-09-20 12:15 UTC, NozomuIkuta commented on src/guide/typescript-support.md
> -    const result = year.value.split('') // => 'split' プロパティは 'number' 型に存在しません
こちら、TypeScriptのエラーメッセージのようですので、原文に戻しました。
また、翻訳の際に文を複製したものが残っていたため、削除しました。

2020-09-20 12:15 UTC, NozomuIkuta commented on src/guide/typescript-support.md
> +    const result = doubleCount.value.split('') // Property 'split' does not exist on type 'number'
こちら、TypeScriptのエラーメッセージのようですので、原文に戻しました。

2020-09-20 18:04 UTC, kazupon commented on src/guide/typescript-support.md
> +## コンポジション API とともに使用する
@potato4d 
>個人的にはカタカナ日本語に訳すのは、あまり意味がない(読み方が分かる程度)のと、訳してかえってわかりにくくなるとという過去の経験から、今後としては技術用語は、原文のままとしておきたいです。

ここで、途中から、このような形にしてしまうと、これまでの翻訳形式と一貫性がなくなってしまうので、引き続き訳すという方向で行きたいと思います。

2020-09-20 18:07 UTC, kazupon commented
@NozomuIkuta 
Composition API については、訳す方向にしたいと思います。
現状翻訳しているので、その内容を取り込みたいと思います。

2020-09-20 18:11 UTC, kazupon approved these changes

2020-09-20 18:12 UTC, kazupon commented
CIでエラー起きているが、これは `review-alert-box` ラベルがないから起きている感じ。
このエラーは特に支障をきたさないので、マージする。

2020-09-20 18:12 UTC, merged

2020-09-20 18:13 UTC, kazupon commented
翻訳ありがとうございました！