API Reference > Basic Reactivity APIs の翻訳
vuejs-jp/ja.vuejs.org pull request #540
Opened 2021-10-15 15:20 UTC by jay-es

## Description of Problem
API Reference > Basic Reactivity APIs を翻訳しました
原文ページ:
https://v3.vuejs.org/api/basic-reactivity.html
## Proposed Solution

## Additional Information

2021-10-20 09:40 UTC, naokie requested changes
@jay-es 
翻訳ありがとうございます！
表記ゆれと、例えについて、2箇所コメントしました。

https://v3.ja.vuejs.org/guide/reactivity.html
https://v3.ja.vuejs.org/guide/reactivity-fundamentals.html
過去にリアクティブガイドを訳しているのですが、このあたりは新しい概念もあって塩梅が難しいですね。

https://developer.mozilla.org/ja/docs/Learn/HTML/Introduction_to_HTML/Getting_started#nesting_elements
いままで「入れ子」と訳してたのですが、割と「ネスト」が一般的なのにも気付かされました

2021-10-20 09:40 UTC, naokie commented on src/api/basic-reactivity.md
> +> このセクションでは、コード例に[シングルファイルコンポーネント](../guide/single-file-component.html)構文を使用します
```suggestion
> このセクションでは、コード例に [単一ファイルコンポーネント](../guide/single-file-component.html) 構文を使用します
```

https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/single-file-component.md
「単一ファイルコンポーネント」で合わせているため、こちらでお願いします。

ref.
https://github.com/vuejs-jp/ja.vuejs.org/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E

2021-10-20 09:40 UTC, naokie commented on src/api/basic-reactivity.md
> +[`reactive`](#reactive) や [`readonly`](#readonly) プロキシの元のオブジェクトを返します。これは、プロキシのアクセス/トラッキングのオーバヘッドを発生させずに一時的に読み込んだり、変更をトリガせずに書き込んだりするために使えるエスケープハッチです。元のオブジェクトへの永続的な参照を保持することは推奨**されません**。注意して使用してください。
例えとして使われている「エスケープハッチ」という表現がカタカナにしてしまうと想像つきづらいので、
日本で一般的に用いられる「避難用ハッチ」か、
丸括弧での補足をつける「エスケープハッチ（脱出口）」か、
どちらかを採用してもらえると！

競走馬の名前にもあるんですね 😆

2021-10-22 14:39 UTC, jay-es commented on src/api/basic-reactivity.md
> +> このセクションでは、コード例に[シングルファイルコンポーネント](../guide/single-file-component.html)構文を使用します
すみません、wiki に気づいていませんでした...:bow:
翻訳ガイドも含め README にリンク記載するとよさそうですね。時間あるときに PR 出します！

2021-10-22 14:48 UTC, jay-es commented on src/api/basic-reactivity.md
> +[`reactive`](#reactive) や [`readonly`](#readonly) プロキシの元のオブジェクトを返します。これは、プロキシのアクセス/トラッキングのオーバヘッドを発生させずに一時的に読み込んだり、変更をトリガせずに書き込んだりするために使えるエスケープハッチです。元のオブジェクトへの永続的な参照を保持することは推奨**されません**。注意して使用してください。
確かにそのままだと不明瞭ですね:pray:
例のゲームにもいるのでしょうか...

2021-10-24 03:10 UTC, kazupon approved these changes
いつもありがとうございます！
私の方でも見ましたが、問題ないです！
レビュー指摘事項修正されているので、マージしますね！

2021-10-24 03:11 UTC, merged