API Reference > Refs の翻訳
vuejs-jp/ja.vuejs.org pull request #545
Opened 2021-10-22 15:50 UTC by jay-es

## Description of Problem
API Reference > Refs  を翻訳しました
原文ページ:
https://v3.vuejs.org/api/refs-api.html

## Proposed Solution

## Additional Information

2021-10-24 03:18 UTC, kazupon commented on src/api/refs-api.md
> +場合によっては、ref の内部値に複合の型を指定する必要があります。そのような場合には、`ref` を呼び出す際にジェネリクス引数を渡して、デフォルトの推論をオーバーライドすることで、簡潔に指定できます。
以下は、読んでいて原文への違和感。(独り言

Generics っていうキーワードが出てきているけど、TypeScript 知っていることを前提にかかれているのかな。 🤔

2021-10-24 03:23 UTC, kazupon commented on src/api/refs-api.md
> +引数が [`ref`](#ref) の場合はその内部の値を、そうでない場合は引数そのものを返します。これは、`val = isRef(val) ? val.value : val` のシュガー関数です。
sugar ですが、プログラミングの文脈ではよく使う言葉なのでその辺に精通している人は、`シュガー`という訳だけで分かるかと思います。ただ、front-end の領域は、それほとプログラミングに精通して~~いる~~いない人が使うことがあるので、ここで注釈も加えて訳にしておいた方がいいです。
`sugar` は文脈的に、簡略的なことを意味していると思うので、`シュガー(簡易)` とかどうでしょうか。

2021-10-24 03:30 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
確認お願いします！ 🙏

2021-10-24 03:30 UTC, kazupon commented on src/api/refs-api.md
> +`toRef` は、prop の ref をコンポジション関数に渡したいときに便利です:
`composition function`  の `composition` は日本語訳の方では、`Composition API` をそのままな形にしてきているので、一貫性を保ちたいです。(そもそも個人的には原文の方は、`composable function` にしたい 😅 )composition (構成:

2021-10-24 03:30 UTC, kazupon commented on src/api/refs-api.md
> +`toRefs` は、コンポジション関数からリアクティブなオブジェクトを返すときに便利で、利用する側のコンポーネントはリアクティビティを失うことなく、返されたオブジェクトを分割代入できます:
ここの `compostion function` の[同じく](https://github.com/vuejs-jp/ja.vuejs.org/pull/545/files#r735056527)

2021-10-29 06:12 UTC, naokie commented on src/api/refs-api.md
> +引数が [`ref`](#ref) の場合はその内部の値を、そうでない場合は引数そのものを返します。これは、`val = isRef(val) ? val.value : val` のシュガー関数です。
「syntax sugar」のシュガーと言われればピンときますが、単体で言われると補足必要ですね 🤔

2021-10-29 13:08 UTC, jay-es commented
修正しました。ご確認よろしくお願いします:pray:

2021-10-29 14:51 UTC, kazupon approved these changes

2021-10-29 14:51 UTC, merged

2021-10-29 14:52 UTC, kazupon commented
@jay-es 
翻訳、ありがとうございました！
マージしました！