Api/composition api
vuejs-jp/ja.vuejs.org pull request #557
Opened 2021-11-03 03:44 UTC by naokie

## Description of Problem

API リファレンスの Composition API を翻訳します。
https://v3.ja.vuejs.org/api/composition-api.html

## Proposed Solution

## Additional Information

2021-11-23 07:51 UTC, kazupon requested changes
大変遅くなりました！
レビュー 👀 コメント 💬 しました。
確認お願いします！

2021-11-23 07:51 UTC, kazupon commented on src/api/composition-api.md
> +コンポーネントオプションは、コンポーネントが作成される **前に**、`props` が解決されると実行されます。これは Composition API のエントリポイントとなります。
そのまま直訳すると少し分かりにくい文章になるので意訳気味に以下でいかがでしょうか。
```suggestion
コンポーネントが作成される **前に**、一度 `props` が解決されると、このコンポーネントオプションが実行されます。Composition API のエントリポイントとして提供します。
```

ポイントとしては、

- `A component option` は `setup` のことを指している。
- `once` も訳す
- `serves` は提供の意味

です。

2021-11-23 07:51 UTC, kazupon commented on src/api/composition-api.md
> +  省略可能なプロパティが、ないことを確認する必要があるなら、デフォルト値として Symbol を指定できます:
以下のように句読点を除いた方が読みやすいと思います。
```suggestion
  省略可能なプロパティがないことを確認する必要があるなら、デフォルト値として Symbol を指定できます:
```

2021-11-23 07:51 UTC, kazupon commented on src/api/composition-api.md
> +  オプション API を使うときの `this.$props` と同様に、`props` オブジェクトには明示的に宣言されたプロパティのみが含まれます。また、すべての宣言されたプロパティのキーは、親コンポーネントから渡されたかどうかに関わらず `props` オブジェクトに存在します。宣言されていない省略可能なプロパティは `undefined` という値になります。
Options API は Composition API の表記とバランスよくしたい (対比のケースだと気になる...) ので、`Options API` のママにしておきたいです。

2021-11-23 07:51 UTC, kazupon commented on src/api/composition-api.md
> +- **オプション API のライフサイクルオプションと Composition API のマッピング**
ここの `Options API` の表記も同じく、そのままで。

2021-11-23 07:51 UTC, kazupon commented on src/api/composition-api.md
> +  Vue は `Symbol` を拡張したジェネリック型の `InjectionKey` インターフェイスを提供しています。これはプロバイダとコンシューマの間で注入された値の型を同期するために使用できます:
`provider` と `cosumer` の訳も悩ましいですね...
個人的には、ソフトウェア用語としてよく出てくる技術word なので、そのままとしておきたいです。
訳すとしたら最初だけ訳スタイルの原文とカッコ付で訳スタイルが折り合い取れていい気がしています。
```suggestion
  Vue は `Symbol` を拡張したジェネリック型の `InjectionKey` インターフェイスを提供しています。これは provider (プロバイダ) と comsumer (コンシューマ) の間で注入された値の型を同期するために使用できます:
```

2021-11-25 09:10 UTC, naokie commented on src/api/composition-api.md
> +  省略可能なプロパティが、ないことを確認する必要があるなら、デフォルト値として Symbol を指定できます:
違和感ないです。ありがとうございます！

2021-11-25 09:10 UTC, naokie commented on src/api/composition-api.md
> +コンポーネントオプションは、コンポーネントが作成される **前に**、`props` が解決されると実行されます。これは Composition API のエントリポイントとなります。
違和感ないです。ありがとうございます！

2021-11-25 09:20 UTC, naokie commented on src/api/composition-api.md
> +  Vue は `Symbol` を拡張したジェネリック型の `InjectionKey` インターフェイスを提供しています。これはプロバイダとコンシューマの間で注入された値の型を同期するために使用できます:
そうですね、ドキュメント内でもここが初出で悩み、カタカナのままの判断にしました。

個人的には、ソフトウェア開発上の用語って、最近は英語のままが違和感なくなってきてますね。
一方で、初学者向けにもと考えたとき、正しい読み方を知ってもらう意味でも、カッコ書きのフォローいいですね。

2021-11-25 10:15 UTC, kazupon approved these changes

2021-11-25 10:15 UTC, kazupon commented
LGTMです！ 👍

2021-11-25 10:15 UTC, merged