docs: translate sfc tooling
vuejs-jp/ja.vuejs.org pull request #571
Opened 2021-11-14 03:17 UTC by naokie

## Description of Problem

API リファレンスの SFC Tooling を翻訳します。
https://v3.ja.vuejs.org/api/sfc-tooling.html

## Proposed Solution

## Additional Information

2021-11-14 06:09 UTC, kazupon commented on src/api/sfc-tooling.md
> +このパッケージは Vue コアの monorepo の一部で、メインの `vue` パッケージと常に同じバージョンで公開されます。通常、プロジェクト内で `vue` の Peer Dependency としてリストアップされます。正しい動作を保証するため、そのバージョンは常に `vue` と同期している必要があります。つまり、`vue` のバージョンをアップグレードするときはいつも、それに合わせ
`monorepo` は `モノレポ` でもよさそうに感じます。日本のブログ記事でもカタカナ表記でみかけるので。

2021-11-14 06:10 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
翻訳内容は問題ありません！

2021-11-15 04:02 UTC, naokie commented on src/api/sfc-tooling.md
> +このパッケージは Vue コアの monorepo の一部で、メインの `vue` パッケージと常に同じバージョンで公開されます。通常、プロジェクト内で `vue` の Peer Dependency としてリストアップされます。正しい動作を保証するため、そのバージョンは常に `vue` と同期している必要があります。つまり、`vue` のバージョンをアップグレードするときはいつも、それに合わせ
ありがとうございます！
自分も若干迷っていたところでした。

2021-11-23 07:57 UTC, kazupon reviewed
レビュー 👀 コメント 💬 しました！
確認お願いします！

2021-11-23 07:57 UTC, kazupon commented on src/api/sfc-tooling.md
> +Vue SFC を試すため、あなたのマシンに何かをインストールする必要はありません。ブラウザ上で操作できるオンラインプレイグラウンドがたくさんあります:
細かいですが、machine の訳気になりますねw
Vue.js docs が想定している利用環境としては、コンピュータのことを言っているに等しいので、以下のようにコンピュータでいい気がします！
```suggestion
Vue SFC を試すため、あなたのコンピュータに何かをインストールする必要はありません。ブラウザ上で操作できるオンラインプレイグラウンドがたくさんあります:
```

2021-11-25 09:21 UTC, naokie commented on src/api/sfc-tooling.md
> +Vue SFC を試すため、あなたのマシンに何かをインストールする必要はありません。ブラウザ上で操作できるオンラインプレイグラウンドがたくさんあります:
自分もそちらのほうがしっくりしたので使わせてもらいます。

2021-11-25 10:15 UTC, kazupon approved these changes

2021-11-25 10:15 UTC, kazupon commented
LGTMです！ 👍

2021-11-25 10:16 UTC, merged