Update reactivity-computed-watchers.md
vuejs-jp/ja.vuejs.org pull request #597
Opened 2021-12-01 09:12 UTC by ZiF1R

2021-12-04 06:45 UTC, kazupon requested changes
翻訳ありがとうございます！ ❤️ 
レビュー 👀 コメント 💬 しておきました。

確認お願いいたします！

2021-12-04 06:45 UTC, kazupon commented on src/guide/reactivity-computed-watchers.md
> +- `onTrack` はリアクティブプロパティまたリンクが依存関係として追跡する時にコールされる。
`ref` は Vue.js のドキュメントの文脈(context)では、ref のことを意味しています。
なので、`ref` そのままでよさそうです。

あと、`コールされる` は `呼び出される` (受動態: passive voice) で訳しておくとよさそうです。

```suggestion
- `onTrack` はリアクティブプロパティまた ref が依存関係として追跡する時に呼び出される。
```

2021-12-04 06:45 UTC, kazupon commented on src/guide/reactivity-computed-watchers.md
> +- `onTrigger` はウォッチのコールバックが依存関係の変更上でトリガーされた時にコールされる。
`watcher` の翻訳は、`ja.v3.vuejs.org` でホストされているドキュメントとしては、`ウォッチャ` にしています。
https://v3.ja.vuejs.org/guide/computed.html#%E3%82%A6%E3%82%A9%E3%83%83%E3%83%81%E3%83%A3

`コールされる` されるも `呼び出される` にする感じで翻訳を考えると、以下のように訳しておくとよさそうです。

```suggestion
- `onTrigger` はウォッチャのコールバックが依存関係の変更上でトリガーされた時に呼び出される。
```

2021-12-04 15:49 UTC, ZiF1R commented on src/guide/reactivity-computed-watchers.md
> +- `onTrigger` はウォッチのコールバックが依存関係の変更上でトリガーされた時にコールされる。
本当にたすかりました。レビューしていただいてありがとうございます！

2021-12-05 13:47 UTC, kazupon approved these changes

2021-12-05 13:47 UTC, merged

2021-12-05 13:47 UTC, kazupon commented
ありがとうございました！