docs: Translate Components In-Depth > Props
vuejs-jp/ja.vuejs.org pull request #60
Opened 2020-09-19 08:49 UTC by n-makoto

resolve #13 Components In-Depth > Props の翻訳

2020-09-20 17:10 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。

対応お願いします！

2020-09-20 17:10 UTC, kazupon commented on src/guide/component-props.md
> +しかし、通常はすべてのプロパティを特定の型の値にしたいと思うでしょう。このような場合には、プロパティをオブジェクトとして列挙し、プロパティのキーと値にそれぞれプロパティの名前と型を設定します。
細かいですが、 `:` は日本語翻訳側の方でも、句点(。)ではなく同じにしておいください！ 🙏

2020-09-23 01:03 UTC, n-makoto commented
@kazupon 
レビューありがとうございます！
指摘いただいた箇所修正しましたのでご確認お願いいたします :pray:

2020-09-23 01:12 UTC, kazupon commented
修正ありがとうございました！
確認しました。
CIでエラーが起きていますが、翻訳に支障はない(別事象)ので、マージしますね！

2020-09-23 01:12 UTC, merged

2020-09-23 01:12 UTC, kazupon commented
翻訳ありがとうございました！

2020-09-24 00:57 UTC, n-makoto commented
こちらこそありがとうございました！貴重な体験が出来て良かったです🙇‍♂️