docs: Advanced Guides > Compotion API > Setup
vuejs-jp/ja.vuejs.org pull request #62
Opened 2020-09-19 10:26 UTC by tutti2612

resolve #33

2020-09-20 18:00 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
確認お願いします！ 🙏

2020-09-21 05:57 UTC, tutti2612 commented
@kazupon 
修正しました。ご確認お願いします！

2020-09-21 14:47 UTC, kazupon approved these changes

2020-09-21 14:48 UTC, kazupon commented
@tutti2612 
確認しました！
ありがとうございます！

CI でエラーになっていますが、このエラー現時点で支障はないので、マージします！

2020-09-21 14:48 UTC, merged

2020-09-21 14:48 UTC, kazupon commented
翻訳ありがとうございました！