docs: #10 Essentials > Form Input Bindings の翻訳
vuejs-jp/ja.vuejs.org pull request #63
Opened 2020-09-19 10:50 UTC by Masa-Shin

resolve #10

2020-09-19 13:14 UTC, Masa-Shin commented
こちらCIが通らないのですが、コード以外の問題（アクセス権限？）のような気がします。

参考
- https://github.com/actions/first-interaction/issues/10#issuecomment-545576314
- https://github.community/t/github-actions-are-severely-limited-on-prs/18179#M9249

2020-09-20 13:01 UTC, Masa-Shin commented
https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-695164725 に関しては、他のPRでは訳していたり訳していなかったりだったので、今回は一旦訳出しない形にしました。

2020-09-20 18:23 UTC, kazupon requested changes
翻訳ありがとうございます！
レビューコメントしました！
対応お願いします！

2020-09-20 18:23 UTC, kazupon commented on src/guide/forms.md
> +単一のチェックボックスと boolean 値：
細かいですが、`：` は半角の `:` でお願いします。
以降も、いくつかありますので、よろしくお願いします 🙏

2020-09-20 18:25 UTC, kazupon commented
GitHub Actoins のエラーは、現状特に支障はないので、一旦無視でお願いします！

2020-09-21 04:53 UTC, Masa-Shin commented
@kazupon 
ありがとうございます！
セミコロンを修正しました。

2020-09-21 14:49 UTC, kazupon approved these changes

2020-09-21 14:50 UTC, kazupon commented
@Masa-Shin 
ありがとうございます！確認しました！
マージします！

2020-09-21 14:50 UTC, merged

2020-09-21 14:50 UTC, kazupon commented
翻訳ありがとうございました！