Reusability & Composition > Render Functions no(#28)
vuejs-jp/ja.vuejs.org pull request #67
Opened 2020-09-20 01:58 UTC by wonderful-panda

## Description of Problem

## Proposed Solution

## Additional Information

2020-09-21 04:02 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
たくさんありますが、確認お願いします！ 🙏 

レビューコメントにもしましたが、大変の内容は、

- 日本語訳の行構成は、原文と同じにする
- 英単語の間にスペース入れる

といったものです。

よろしくお願いします！

2020-09-21 04:07 UTC, kazupon commented
行構成のレビューコメント、所々 原文の方にしていますが、日本語訳の行構成を英語と同じようにしてほしいという意図でしています。
わかりにくくてすいません。

2020-09-22 06:26 UTC, wonderful-panda commented
レビューありがとうございます。修正したものをpushしました。

2020-09-22 15:38 UTC, kazupon commented
修正内容確認しました！
翻訳ありがとうございました！
CIでエラーが発生していますが、翻訳作業に支障がないので、マージします！

2020-09-22 15:38 UTC, kazupon approved these changes

2020-09-22 15:38 UTC, merged