docs #26 Reusability & Composition > Custom Directives の翻訳
vuejs-jp/ja.vuejs.org pull request #68
Opened 2020-09-20 08:32 UTC by egurinko

resolved https://github.com/vuejs-jp/ja.vuejs.org/issues/26

2020-09-21 15:10 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
翻訳内容はほぼ完璧です！

ほとんどは細かい内容のものですが、対応お願いします！ 🙏

2020-09-21 15:10 UTC, kazupon commented on src/guide/custom-directive.md
> +:::tip 注意
VuePress の `:::` のやつですが、以下でも質問がありましたが、一旦翻訳しない方向に決めました。
https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-695164725
ですので、そのままにしておいてください。 🙏 
```suggestion
:::tip Note
```

2020-09-21 15:10 UTC, kazupon commented on src/guide/custom-directive.md
> +- `updated`: バインドされた要素を含むコンポーネントの VNode **とその子コンポーネントの VNode** が更新された後に呼ばれます。
ここの bind も同じく。
```suggestion
- `updated`: 束縛された要素を含むコンポーネントの VNode **とその子コンポーネントの VNode** が更新された後に呼ばれます。
```

2020-09-21 15:10 UTC, kazupon commented on src/guide/custom-directive.md
> +- `beforeUnmount`: バインドされた要素の親コンポーネントがアンマウントされる前に呼ばれます。
ここの bind も同じく。
```suggestion
- `beforeUnmount`: 束縛された要素の親コンポーネントがアンマウントされる前に呼ばれます。
```

2020-09-21 15:10 UTC, kazupon commented on src/guide/custom-directive.md
> +- `unmounted`: ディレクティブが要素からバインドを解かれた時、また親コンポーネントがアンマウントされた時に1度だけ呼ばれます。
ここの bind も同じく。
```suggestion
- `unmounted`: ディレクティブが要素から束縛されなくなった時、また親コンポーネントがアンマウントされた時に1度だけ呼ばれます。
```

2020-09-21 15:10 UTC, kazupon commented on src/guide/custom-directive.md
> +このカスタムディレクティブは、いくつかの違うユースケースをサポートできるほど柔軟になりました。さらに動的にするには、バインドした値を修正できるようにすれば良いでしょう。`pinPadding` という追加のプロパティを作成して、`<input type="range">` にバインドしてみましょう。
ここの bind も同じく。
```suggestion
このカスタムディレクティブは、いくつかの違うユースケースをサポートできるほど柔軟になりました。さらに動的にするには、束縛した値を修正できるようにすれば良いでしょう。`pinPadding` という追加のプロパティを作成して、`<input type="range">` に束縛してみましょう。
```

2020-09-26 12:15 UTC, egurinko commented on src/guide/custom-directive.md
> +ここからこれを実現するディレクティブを実装しましょう。
ご指摘ありがとうございます！
https://github.com/vuejs-jp/ja.vuejs.org/pull/68/commits/25049608a15dd9d390003802a2214a2593c1eb07 にて修正を入れさせていただきました 🙏

2020-09-26 12:17 UTC, egurinko commented on src/guide/custom-directive.md
> +  // バインドされている要素が DOM にマウントされると...
承知しました！
こちら https://github.com/vuejs-jp/ja.vuejs.org/pull/68/commits/63bedfb0e23c0f0961274fd3b9f797f38edd5187 にてまとめて修正させていただきました 🙋

2020-09-26 12:19 UTC, egurinko commented on src/guide/custom-directive.md
> +:::tip 注意
なるほど！ご指摘ありがとうございます！
こちらも原文表示に修正しました!
https://github.com/vuejs-jp/ja.vuejs.org/pull/68/commits/ee56f7467064235da88d0291f9768ea496b68ba9

2020-09-26 12:20 UTC, egurinko commented
> レビュー 👀 コメント 💬 しました！
> 翻訳内容はほぼ完璧です！
> 
> ほとんどは細かい内容のものですが、対応お願いします！ 🙏

細かくレビューいただきありがとうございました！
対応完了いたしました！

2020-09-26 15:15 UTC, kazupon approved these changes

2020-09-26 15:16 UTC, kazupon commented
指摘事項の対応ありがとうございました！
確認しました！
LGTMです！

CIでエラーが起きていますが、翻訳作業に支障はない(このPRとは別事象)ので、マージします！

翻訳ありがとうございました！

2020-09-26 15:17 UTC, merged