docs: Translate Advanced Guides > Reactivity in Depth
vuejs-jp/ja.vuejs.org pull request #70
Opened 2020-09-20 16:44 UTC by t0yohei

resolve #30

2020-09-20 16:46 UTC, t0yohei commented on src/guide/reactivity.md
> +<VideoLesson href="https://www.vuemastery.com/courses/vue-3-reactivity/vue3-reactivity" title="Learn how how reactivity works in depth with Vue Mastery">Vue Mastery のリアクティブの探求に関する無料ビデオを視聴する</VideoLes
[memo]
この部分は 2020/09/18 に追加された下記の2コミットへの対応です。
- https://github.com/vuejs/docs-next/commit/dec96b373f18a3f69ce21dc3b6e76daa84a9fcd7#diff-b763cbaff1979124456c40cefa92bd81
- https://github.com/vuejs/docs-next/commit/8d8d19042ebf18110cf08fa8d10ad977f3fd5e82#diff-b763cbaff1979124456c40cefa92bd81

2020-09-21 15:27 UTC, kazupon commented on src/guide/reactivity.md
> +<VideoLesson href="https://www.vuemastery.com/courses/vue-3-reactivity/vue3-reactivity" title="Learn how how reactivity works in depth with Vue Mastery">Vue Mastery のリアクティブの探求に関する無料ビデオを視聴する</VideoLes
ありがとうございます！

2020-09-21 15:40 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
確認お願いします！ 🙏

2020-09-21 15:40 UTC, kazupon commented on src/guide/reactivity.md
> +最初のレンダリングの後、コンポーネントはレンダリング中にアクセスしたプロパティを依存関係一覧として追跡します。逆に言えば、コンポーネントはこれらの各プロパティのサブスクライバーになります。プロキシがセット処理を傍受すると、プロパティはサブスクライブされているすべてのコンポーネントに再レンダリングを通知します。
`subscriber` 、`subscribed` も訳 + 意訳して以下のようにしておいてください！ 🙏 
```suggestion
最初のレンダリングの後、コンポーネントはレンダリング中にアクセスしたプロパティを依存関係一覧として追跡します。逆に言えば、コンポーネントはこれらの各プロパティの値を監視する購読者になります。プロキシがセット処理を傍受すると、プロパティは購読されているすべてのコンポーネントに再レンダリングを通知します。
```

2020-09-22 09:00 UTC, t0yohei commented on src/guide/reactivity.md
> +最初のレンダリングの後、コンポーネントはレンダリング中にアクセスしたプロパティを依存関係一覧として追跡します。逆に言えば、コンポーネントはこれらの各プロパティのサブスクライバーになります。プロキシがセット処理を傍受すると、プロパティはサブスクライブされているすべてのコンポーネントに再レンダリングを通知します。
レビューありがとうございます！以下のコミットで対応いたしました。
https://github.com/vuejs-jp/ja.vuejs.org/pull/70/commits/dc2300b7f355748f8bc9332f21a8b4b194ef606a

2020-09-22 15:25 UTC, kazupon commented
ありがとうございます
修正確認しました！

CIでエラーが起きていますが、翻訳に支障がないので、マージします。

2020-09-22 15:26 UTC, merged