Essentials > Computed Properties and Watchers の翻訳
vuejs-jp/ja.vuejs.org pull request #72
Opened 2020-09-21 09:39 UTC by jay-es

resolve #49

v2 のドキュメントと内容はほぼ同じでしたが、「一語一句翻訳」のガイドラインに沿って翻訳しなおしました。
以下の用語（や見出し）は v2 の訳を踏襲してあります。
```
getter → getter 関数
setter → setter 関数
watcher/watchers → ウォッチャ
watched property → 監視プロパティ
Computed Caching vs Methods → 算出プロパティ vs メソッド
```

2020-09-21 09:47 UTC, jay-es commented on src/guide/computed.md
> +ずっといいですよね？
原文に合わせ、なるべく短く、かつ少しだけくだけた感じを目指しました。
これを再翻訳すると原文と同じになります。
https://www.deepl.com/ja/translator#ja/en/%E3%81%9A%E3%81%A3%E3%81%A8%E3%81%84%E3%81%84%E3%81%A7%E3%81%99%E3%82%88%E3%81%AD%EF%BC%9F

別のニュアンスの代案として「ぐっとよくなりましたね？」があります
https://www.deepl.com/ja/translator#ja/en/%E3%81%90%E3%81%A3%E3%81%A8%E3%82%88%E3%81%8F%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%97%E3%81%9F%E3%81%AD%EF%BC%9F

2020-09-21 16:34 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
いくつか対応お願いします。

2020-09-21 16:34 UTC, kazupon commented on src/guide/computed.md
> +そのため、リアクティブなデータを含む複雑なロジックには**算出プロパティ**を使いましょう。
`you should use a **computed property**.` の訳ですが、文章の流れから、ここでの `should` は義務、当然の行為を表す `〜すべき` で訳すのが自然だと思います。
なので、以下でお願いします。

```suggestion
そのため、リアクティブなデータを含む複雑なロジックには**算出プロパティ**を使うべきです。
```

2020-09-21 16:34 UTC, kazupon commented on src/guide/computed.md
> +通常のプロパティと同じように、テンプレート内で算出プロパティにデータバインドできます。Vue は `vm.publishedBooksMessage` が `vm.author.books` に依存していると分かっているので、`vm.author.books` が変更されると `vm.publishedBooksMessage` に依存するバインディングを更新します。また、この依存関係を宣言的に
`And the best part is that we've created this dependency relationship declaratively` の訳ですが、`また、この依存関係を宣言的に作成しているのが最高です` では、ちょっと言い回しが砕けすぎなので、以下のような感じでお願いします。
```
そして、一番よいのは、この依存関係を宣言的に作成していることです。
```

2020-09-21 16:34 UTC, kazupon commented on src/guide/computed.md
> +下の算出プロパティは `Date.now()` がリアクティブな依存関係ではないので、一度も更新されないことになります:
typo しているので以下でお願いします。
```suggestion
以下の算出プロパティは `Date.now()` がリアクティブな依存関係ではないので、一度も更新されないことになります:
```

2020-09-21 16:34 UTC, kazupon commented on src/guide/computed.md
> +ずっといいですよね？
そうですね。
ここの `Much better, isn't it?` は、この文章の流れ的に、砕けた感じでも大丈夫そうです。
`ずっといいですよね？`で、いいと思います。

2020-09-22 01:48 UTC, jay-es commented
修正完了しましたので、ご確認よろしくお願いします。

2020-09-22 08:40 UTC, kazupon approved these changes

2020-09-22 08:41 UTC, kazupon commented
@jay-es 
確認しました！
ありがとうございます！
LGTM 👍 です！

CI でエラーが起きていますが、特に支障がないのでマージします。

2020-09-22 08:41 UTC, merged

2020-09-22 08:42 UTC, kazupon commented
翻訳ありがとうございました！