WIP FIX #14 Components In-Depth > Non-Prop Attributes の翻訳
vuejs-jp/ja.vuejs.org pull request #74
Opened 2020-09-21 14:56 UTC by mikakane

## Description of Problem

## Proposed Solution

## Additional Information

2020-09-21 16:42 UTC, kazupon reviewed
レビュー 👀 しました。
指摘コメント 💬 の対応お願いします。

2020-09-21 16:42 UTC, kazupon commented on src/guide/component-attrs.md
> +[previous section]('#属性の継承) で利用した date-picker のコンポーネント例を用いて、プロパティでない属性の全てを ルートの `div` 要素ではなく `input` 要素に適用する場合、`v-bind` を用いて簡略的に記述することも可能です。
`previous section` も訳せるので、以下のようにお願いします。

```suggestion
[前節]('#属性の継承) で利用した date-picker のコンポーネント例を用いて、プロパティでない属性の全てを ルートの `div` 要素ではなく `input` 要素に適用する場合、`v-bind` を用いて簡略的に記述することも可能です。
```

2020-09-22 03:41 UTC, mikakane commented
上記の修正と合わせて class / id / style に関する認識違いがあったので修正しました。
4d4d1d4

2020-09-22 03:43 UTC, mikakane commented
$attr で class / id / style にアクセスできるようになったんですが、「Non props Attribute 」にはこのclass / id / style  を含むんでしょうか？

冒頭の、

> A component non-prop attribute is an attribute or event listener that is passed to a component, but does not have a corresponding property defined in [props](component-props) or [emits](component-custom-events.html#defining-custom-events). Common examples of this include `class`, `style`, and `id` attributes.

で、`this include` が全文主節にかかるのか but 節にかかるのかちょっと不明で判断しきれなかったです。

2020-09-22 15:18 UTC, kazupon requested changes
[こちら](https://github.com/vuejs-jp/ja.vuejs.org/pull/74#issuecomment-696492867)について回答する形で、再度レビューしました。確認お願いします。

2020-09-22 15:18 UTC, kazupon commented on src/guide/component-attrs.md
> +プロパティでない属性とは、コンポーネントに渡される属性やイベントリスナのうち、[props](component-props) や [emits](component-custom-events.html#defining-custom-events) で定義されたものを除いたものをいいます。なお、共通の認識として `class` や `style`, `id` 属性はここに含まれません。
[こちらのURLの件](https://github.com/vuejs-jp/ja.vuejs.org/pull/74#issuecomment-696492867)、ここで回答しますね。

>$attr で class / id / style にアクセスできるようになったんですが、「Non props Attribute 」にはこのclass / id / style を含むんでしょうか？

恐らく `$attr` は `$attrs` の typo だと思いますが、 `$attrs` と想定して回答すると、
この 「Non-Prop Attributes」 においては含まれますね。

DOM の `id` / `class` / `style` といった 属性、 click 、mousemove といったイベントは、コンポーネントの `props` 、`emits` で定義しなければ、 `$attrs` でアクセス可能になります。
これら DOM の属性、イベントをコンポーネントの`props` 、`emits`で定義した場合は、コンポーネント側で使用するため、`$attrs` でアクセスできなくなります。

「Non-Prop Attributes」では、用は `$attrs` について解説しています。

なので、

> A component non-prop attribute is an attribute or event listener that is passed to a component, but does not have a corresponding property defined in [props](component-props) or [emits](component-custom-events.html#defining-custom-events). Common examples of this include `class`, `style`, and `id` attributes.

の訳は、わかりやすくするために、意訳も入れて以下にするといいかと思います。

```suggestion
プロパティでない属性とは、コンポーネントに渡される属性やイベントリスナのうち、[props](component-props) や [emits](component-custom-events.html#defining-custom-events) で定義されたものを除いたものをいいます。一般の例としてはコンポーネント内の要素に渡す DOM の `class` 、`style` 、`id` 属性があります。
```

2020-09-22 15:18 UTC, kazupon commented on src/guide/component-attrs.md
> +`inheritAttrs` を `false` にセットした場合、コンポーネントの `$attrs` プロパティを通じて、`props` や `emits`といったコンポーネントのプロパティを除く全ての属性(例えば`class` や `style` 、 `v-on` といったものも)にアクセスできるようになります。
これ、原文がちょっと書き方よくない気がする...
`inheritAttrs` の値 `true/false` どちらでも、`props` 、`emits` に定義されていない属性やイベントハンドラにアクセスできるのが今の仕様。

2020-09-23 05:20 UTC, mikakane commented on src/guide/component-attrs.md
> +`inheritAttrs` を `false` にセットした場合、コンポーネントの `$attrs` プロパティを通じて、`props` や `emits`といったコンポーネントのプロパティを除く全ての属性(例えば`class` や `style` 、 `v-on` といったものも)にアクセスできるようになります。
ですよね、そこの値で $attrs の有無がスイッチスルことはないと思うんですが。原文と挙動どっちに準拠するほうがよいです？

2020-09-23 05:25 UTC, mikakane commented on src/guide/component-attrs.md
> +プロパティでない属性とは、コンポーネントに渡される属性やイベントリスナのうち、[props](component-props) や [emits](component-custom-events.html#defining-custom-events) で定義されたものを除いたものをいいます。なお、共通の認識として `class` や `style`, `id` 属性はここに含まれません。
ありがとうございます。

次のセクションで `data-status` 属性の例示をしていることから考えても、
ここでの  `class` 、`style` 、`id` は 典型例ではなく、特記(v3での変更点)のような性質に近いものだと思っているんですが、 `一般の例としては` という形の表現で問題ないですか？

2020-09-23 15:41 UTC, kazupon commented on src/guide/component-attrs.md
> +プロパティでない属性とは、コンポーネントに渡される属性やイベントリスナのうち、[props](component-props) や [emits](component-custom-events.html#defining-custom-events) で定義されたものを除いたものをいいます。なお、共通の認識として `class` や `style`, `id` 属性はここに含まれません。
`commons` の `common` の訳は、「共通」とか以外に、「ありふれた」「よくある」などの意味があります。
DOM の属性において、`class` / `style` / `id` はよく使うものなので、`commons examples` を「一般の例としては」のように訳しても問題ない思います。

2020-09-23 15:44 UTC, kazupon commented on src/guide/component-attrs.md
> +`inheritAttrs` を `false` にセットした場合、コンポーネントの `$attrs` プロパティを通じて、`props` や `emits`といったコンポーネントのプロパティを除く全ての属性(例えば`class` や `style` 、 `v-on` といったものも)にアクセスできるようになります。
これ、原文直した方がいいですね。これ、自分 PR 送ってなおしておきます。
なので、`inheritAttrs` の boolean 値でトグルに関わらず、$attrs にアクセスできる、という内容を想定した訳にしていただきたいです。

2020-09-24 05:06 UTC, kazupon commented
本家ドキュメントにPR送って反映させました。

https://github.com/vuejs/docs-next/pull/541

多分、これで違和感なくなると思います

2020-09-24 11:46 UTC, mikakane commented
@kazupon 上記修正してみました！

2020-09-24 14:46 UTC, kazupon commented
対応ありがとうございます。
確認しました！
LGTMです。

CIでエラーが起きていますが、翻訳作業に支障がない(このPRとは別事象)ので、マージします。

2020-09-24 14:46 UTC, kazupon approved these changes

2020-09-24 14:47 UTC, merged