docs: Components In-Depth > Component Registration の翻訳
vuejs-jp/ja.vuejs.org pull request #75
Opened 2020-09-21 16:41 UTC by HomMarkHunt

resolve #12 

## Description of Problem

## Proposed Solution

## Additional Information

2020-09-21 16:45 UTC, HomMarkHunt commented on src/guide/component-registration.md
> -The name you give a component may depend on where you intend to use it. When using a component directly in the DOM (as opposed to in a string template or [single-file component](../guide/single-file-
かなり細かいですが `directly in the DOM(` の閉じ括弧がつけて忘れているのかな？と判断したので `as opposed to in a string template or [single-file component](../guide/single-file-component.html)` までを括弧として翻訳しました。勘違いでしたら申し訳ございません。

2020-09-22 16:28 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> -The name you give a component may depend on where you intend to use it. When using a component directly in the DOM (as opposed to in a string template or [single-file component](../guide/single-file-
これ、括弧の閉じ忘れですね... (本家へ PR contribution のいい機会ですね！)

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> +その他のコンポーンメント名の推奨項目は [スタイルガイド](../style-guide/#base-component-names-strongly-recommended) で確認することができます。
typoですね。
```suggestion
その他のコンポーネント名の推奨項目は [スタイルガイド](../style-guide/#base-component-names-strongly-recommended) で確認することができます。
```

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> +ES2015+ の場合、`ComponentA` のような変数名をオブジェクト内に配置することは `ComponentA: ComponentA` の省略記法にあたり、変数の名前は次のどちらも意味することに注意して下さい:
`ES2015+` は `ES2015 以降` で訳せそうです。

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> +もし `import`/`require` を使用したモジュールシステムを使わないのであれば, このセクションはスキップスキップすることができます。そうでなければ、いくつかのインストラクションと tips をお伝えします。
- typoがありました。
- `tips`はコツ、秘訣、裏技とか訳せそうです。
- ドキュメントでは `お伝えします`とかしこまらなくていいです。 ここでは`教えます` と訳してみました。

```suggestion
もし `import`/`require` を使用したモジュールシステムを使わないのであれば, このセクションはスキップすることができます。そうでなければ、いくつかのインストラクションとコツを教えます。
```

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> +もしまだこの記事をご覧になっているということは、Webpack や Babel のようなモジュールシステムを利用しているのかと思います。このような場合は、それぞれのコンポーネントを独自のファイルに持つ `components` ディレクトリを作成することをお勧めします。
ドキュメントのトーンを合わせたいので以下のように訳していただきたいです。 🙏 

```suggestion
もしまだこの記事を読んでいるということは、Webpack や Babel のようなモジュールシステムを利用している可能性が高いでしょう。このような場合は、それぞれのコンポーネントを独自のファイルに持つ `components` ディレクトリを作成することをお勧めします。
```

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> +次にローカル登録をする前に、使用するコンポーネントごとにインポートする必要があります。例えば、`ComponentB.js` もしくは `ComponentB.vue` ファイル:
読者にドキュメントの説明が、不自然にならないように以下のような形で、自然にしてもらいたいです  🙏 
```suggestion
次にローカル登録をする前に、使用するコンポーネントごとにインポートする必要があります。例えば、`ComponentB.js` もしくは `ComponentB.vue` ファイルの場合:
```

2020-09-22 16:28 UTC, kazupon commented on src/guide/component-registration.md
> +グローバル登録はしばしば理想的ではありません。例えば、Webpack のようなビルドシステムを利用した場合、全てのコンポーネントをグローバル登録すると、使用していないコンポーネントも最終ビルドに含まれてしまいます。これはユーザがダウンロードしなければならない JavaScript の量を不必要に増やしてしまう事になります。
```suggestion
グローバル登録はしばしば理想的ではありません。例えば、Webpack のようなビルドシステムを利用した場合、全てのコンポーネントをグローバル登録すると、使用していないコンポーネントも最終ビルドに含まれてしまいます。これはユーザーがダウンロードしなければならない JavaScript の量を不必要に増やしてしまう事になります。
```

2020-09-29 11:56 UTC, HomMarkHunt commented
@kazupon 
対応遅くなってしまい申し訳ございません
頂いたレビュー箇所修正いたしましたのでご確認お願いします

2020-09-29 12:30 UTC, HomMarkHunt commented on src/guide/component-registration.md
> -The name you give a component may depend on where you intend to use it. When using a component directly in the DOM (as opposed to in a string template or [single-file component](../guide/single-file-
せっかくなので送ってみました
https://github.com/vuejs/docs-next/pull/568

2020-09-29 14:29 UTC, kazupon requested changes
typoだけありますので、よろしくお願いします！ 🙏

2020-09-29 14:29 UTC, kazupon commented on src/guide/component-registration.md
> +ES2015 移行の場合、`ComponentA` のような変数名をオブジェクト内に配置することは `ComponentA: ComponentA` の省略記法にあたり、変数の名前は次のどちらも意味することに注意して下さい:
typoですね 😎 
```suggestion
ES2015 以降の場合、`ComponentA` のような変数名をオブジェクト内に配置することは `ComponentA: ComponentA` の省略記法にあたり、変数の名前は次のどちらも意味することに注意して下さい:
```

2020-09-29 17:14 UTC, HomMarkHunt commented
@kazupon 
何度も申し訳ございません🙏🙏🙏
最後のtypoも修正いたしました🙏🙏🙏

2020-09-30 06:22 UTC, kazupon approved these changes

2020-09-30 06:23 UTC, kazupon commented
対応ありがとうございました！
確認しました。
CIでエラーが起きていますが、翻訳作業に支障はない(このPRとは別事象)ので、マージしますね。

翻訳ありがとうございました！

2020-09-30 06:23 UTC, merged