docs: #17 翻訳 "Components In-Depth > Provide / inject"
vuejs-jp/ja.vuejs.org pull request #79
Opened 2020-09-22 09:47 UTC by mtmtkzm

resolve #17

`/guide/component-provide-inject.html`の翻訳

2020-09-22 16:06 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2020-09-22 16:06 UTC, kazupon commented on src/guide/component-provide-inject.md
> +前述の例では、リスト `todos` を変更しても、その変更は注入された `todoLength` には反映されません。これは、`provide/inject` の束縛（ binding ）がデフォルトでリアクティブ _でない_ ことが原因です。プロパティ `ref` やオブジェクト `reactive` を `provide` に渡すことにより、この振る舞いを変更することができます。この場合、
- 「`ref` property or `reactive` object」ですが、以下のような、意訳した方がよさそうです。
- `Composition API` は `コンポジション API` の訳で統一します。
- 「`computed` property」は `computed` で定義されたプロパティ
- ... etc

これらをふまえて、以下の訳でお願いします！

```suggestion
前述の例では、リスト `todos` を変更しても、その変更は注入された `todoLength` には反映されません。これは、`provide/inject` の束縛（ binding ）がデフォルトでリアクティブ _でない_ ことが原因です。`ref` で定義されたプロパティや `reactive` で作成されたオブジェクトを `provide` に渡すことにより、この振る舞いを変更することができます。この場合、祖先コンポーネントをリアクティブにするためには、コンポジション API の `computed` で定義したプロパティを `todoLength` を割り当てる必要があります。
```

2020-09-22 16:06 UTC, kazupon commented on src/guide/component-provide-inject.md
> +こうすると、`todos.length`へのあらゆる変更が、`todoLength` が注入されたコンポーネントに正しく反映されます。`reactive` の provide/inject の詳細については、[Composition API セクション](composition-api-provide-inject.html#injection-reactivity) をご覧ください。
`Compostion API` は以下の訳でお願いします！
```suggestion
こうすると、`todos.length`へのあらゆる変更が、`todoLength` が注入されたコンポーネントに正しく反映されます。`reactive` の provide/inject の詳細については、[コンポジション API セクション](composition-api-provide-inject.html#injection-reactivity) をご覧ください。
```

2020-09-23 14:15 UTC, mtmtkzm commented
@kazupon ご丁寧にレビューありがとうございました！勉強になります。
レビュー箇所拝見し、ありがたく suggestion を GitHubからコミットさせていただきました 🤩

2020-09-23 15:15 UTC, kazupon approved these changes

2020-09-23 15:16 UTC, kazupon commented
対応ありがとうございます！
確認しました。
CIでエラーが発生していますが、翻訳作業に支障がない(このPRとは別事象)なので、マージします。

2020-09-23 15:16 UTC, merged

2020-09-23 15:16 UTC, kazupon commented
翻訳ありがとうございました！