docs: Components In-Depth > Template refs の翻訳
vuejs-jp/ja.vuejs.org pull request #81
Opened 2020-09-22 10:39 UTC by ushironoko

resolve #19 

Components In-Depth > Template refs の翻訳

2020-09-22 16:59 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2020-09-22 16:59 UTC, kazupon commented on src/guide/component-template-refs.md
> +# Template refs について
このセクションは、`$refs` を使ったテンプレートの参照の仕方について解説しています。
なので、以下のように訳しましょう。
```suggestion
# テンプレート参照について
```

2020-09-22 16:59 UTC, kazupon commented on src/guide/component-template-refs.md
> +プロップやイベントが存在するにもかかわらず、 JavaScript で子コンポーネントに直接アクセスしなければならない場合があります。それを達成するために、`ref` 属性を使うことで子コンポーネントや HTML 要素に参照IDを割り当てられます。例えば、以下のようになります:
- この文章での `props` は、以下のように、文章の文脈上、`プロパティ` と訳しましょう。
- Vue 公式ドキュメントの翻訳はこれまでに読みやすさのために日本語文章に英単語がある場合はスペース入れてきました。なので、スペース入れていきましょう。

以下でお願いします！
```suggestion
プロパティやイベントが存在するにもかかわらず、 JavaScript で子コンポーネントに直接アクセスしなければならない場合があります。それを達成するために、`ref` 属性を使うことで子コンポーネントや HTML 要素に参照 ID を割り当てられます。例えば、以下のようになります:
```

2020-09-22 16:59 UTC, kazupon commented on src/guide/component-template-refs.md
> +**こちらも参照してください**: [コンポジションAPIでTemplate refsを使用する](/guide/composition-api-template-refs.html#template-refs)
これまでのレビューコメントから、以下でお願いします 🙏 

```suggestion
**こちらも参照してください**: [コンポジション API でテンプレート参照を使用する](/guide/composition-api-template-refs.html#template-refs)
```

2020-09-23 11:39 UTC, ushironoko commented
@kazupon 
レビューありがとうございます。該当箇所を修正したのでご確認お願いします🙏

2020-09-23 15:12 UTC, kazupon commented
ありがとうございます！
修正確認しました！
CIでエラーが起きていますが、翻訳作業に支障はない(別事象)のため、マージします。

翻訳ありがとうございました！

2020-09-23 15:12 UTC, kazupon approved these changes

2020-09-23 15:12 UTC, merged