docs: Advanced Guides > Reactivity Fundamentals の翻訳 (#31)
vuejs-jp/ja.vuejs.org pull request #82
Opened 2020-09-22 11:03 UTC by mascii

resolve #31

Advanced Guides > Reactivity Fundamentals の翻訳

2020-09-22 17:01 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +JavaScript のオブジェクトからリアクティブな状態を作る目的で、`reactive` メソッドを用いることができます:
本家へフィードバックするための個人的なMEMO: 
`reactive` メソッドは違和感がある。すべては function だと思う。

2020-09-22 17:27 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2020-09-22 17:27 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +`reactive` についての詳細は [Basic Reactivity API](../api/basic-reactivity.html) セクションを参照してください
`Basic Reactivity API` は以下のような訳お願いします。
```suggestion
`reactive` についての詳細は [基本 リアクティビティ API](../api/basic-reactivity.html) セクションを参照してください
```

2020-09-22 17:27 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +ref がレンダーコンテキスト([setup()](composition-api-setup.html) によって返されるオブジェクト)のプロパティとして返されていてテンプレート内でアクセスされる場合、自動的に内部の値にアンラップされます。テンプレート内においては `.value` を付ける必要はありません:
- `レンダーコンテキスト` ですが、このままでもいいですが、なるべくカタカナ日本語翻訳で意味がわからなくなった場合でも分かるように、原文も付加した形でにしておいてください
- アンラップが wrap という概念に疎い人にはわかリにくいので、意訳する形にしました

```suggestion
ref がレンダーコンテキスト(render contenxt)([setup()](composition-api-setup.html) によって返されるオブジェクト)のプロパティとして返されていてテンプレート内でアクセスされる場合、自動的に内部の値にアンラップ(ref でラップされた値を元に値の状態に戻す)されます。テンプレート内においては `.value` を付ける必要はありません:
```

2020-09-22 17:27 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +## 独立したリアクティブな値を `refs` として作成する
`refs` ですが、原文は `references` だと長いので `refs` に略しています。
日本語訳の方は、`refs` は以下の参照としておいてください。
```suggestion
## 独立したリアクティブな値を `参照` として作成する
```

2020-09-22 17:27 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +`refs` についての詳細は [Refs API](../api/refs-api.html#ref) セクションを参照してください
以下の意訳でお願いします。
```suggestion
`ref` で作成した `参照` についての詳細は [参照 (refs) API](../api/refs-api.html#ref) セクションを参照してください
```

2020-09-23 00:07 UTC, mascii commented on src/guide/reactivity-fundamentals.md
> +ref がレンダーコンテキスト([setup()](composition-api-setup.html) によって返されるオブジェクト)のプロパティとして返されていてテンプレート内でアクセスされる場合、自動的に内部の値にアンラップされます。テンプレート内においては `.value` を付ける必要はありません:
- レンダーコンテキストの部分について、 () が二回連続し少々読みづらく感じたのですが、L34 での表記とあわせて「(render contenxt - [setup()](composition-api-setup.html) によって返されるオブジェクト)」のように変更しても良いでしょうか？
- 意訳「ref でラップされた値を元に値の状態に戻す」について、"state" の意味での「状態」との混同を避けるため「ref でラップされた値を取り出す」という表現が良いかと考えましたが、いかがでしょうか？

2020-09-23 00:11 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +ref がレンダーコンテキスト([setup()](composition-api-setup.html) によって返されるオブジェクト)のプロパティとして返されていてテンプレート内でアクセスされる場合、自動的に内部の値にアンラップされます。テンプレート内においては `.value` を付ける必要はありません:
>「(render contenxt - setup() によって返されるオブジェクト)」のように変更しても良いでしょうか？

それでも大丈夫です。確かに、括弧が地続きですと、読みづらいですね。

2020-09-23 00:13 UTC, kazupon commented on src/guide/reactivity-fundamentals.md
> +ref がレンダーコンテキスト([setup()](composition-api-setup.html) によって返されるオブジェクト)のプロパティとして返されていてテンプレート内でアクセスされる場合、自動的に内部の値にアンラップされます。テンプレート内においては `.value` を付ける必要はありません:
>"state" の意味での「状態」との混同を避けるため「ref でラップされた値を取り出す」という表現が良いかと考えましたが、いかがでしょうか？

確かに「値の状態に戻す」 ですと `state` と間違いやすいですね。その案でいいと思います。

2020-09-23 12:32 UTC, mascii commented
@kazupon ご指摘いただいていた箇所について 4d425c98a2492af8c095c10ef2bdcb1ca25f7361 で修正しましたので、ご確認お願いいたします。

2020-09-23 15:20 UTC, kazupon approved these changes

2020-09-23 15:20 UTC, merged

2020-09-24 00:44 UTC, mascii commented
@kazupon レビューいただきありがとうございました！