docs: Reusability & Composition > Mixins の翻訳
vuejs-jp/ja.vuejs.org pull request #83
Opened 2020-09-22 12:57 UTC by Nag729

resolve #25 
Reusability & Composition > Mixins の翻訳

レビューよろしくお願いします！

2020-09-22 17:32 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2020-09-22 17:32 UTC, kazupon commented on src/guide/mixins.md
> +これらの問題に対処するため、論理的な関心事によってコードを整理する新しい方法を追加しました: [Composition API](composition-api-introduction.html)
`Composition API` の訳は以下のように統一させてください。:pray:
```suggestion
これらの問題に対処するため、論理的な関心事によってコードを整理する新しい方法を追加しました: [コンポジション API](composition-api-introduction.html)
```

2020-09-22 17:32 UTC, kazupon commented on src/guide/mixins.md
> +ご覧の通り、コンソールには最初にミックスインから、次に `app` から出力された `toVal` と `fromVal` が表示されます。`fromVal` が存在する場合には常にそれが返されるため、最終的には `this.$options.custom` に `hello!` がセットされます。ストラテジを*常に子インスタンスの値を返す*ように変更してみましょう:
`ご覧の通り` は、これまでの Vue 公式ドキュメントの翻訳トーンに合わないので以下の意訳でお願いします！
```suggestion
上記の通り、コンソールには最初にミックスインから、次に `app` から出力された `toVal` と `fromVal` が表示されます。`fromVal` が存在する場合には常にそれが返されるため、最終的には `this.$options.custom` に `hello!` がセットされます。ストラテジを*常に子インスタンスの値を返す*ように変更してみましょう:
```

2020-09-24 15:16 UTC, Nag729 commented on src/guide/mixins.md
> +これらの問題に対処するため、論理的な関心事によってコードを整理する新しい方法を追加しました: [Composition API](composition-api-introduction.html)
Suggested change に沿って修正を行いました。

2020-09-24 15:17 UTC, Nag729 commented on src/guide/mixins.md
> +ご覧の通り、コンソールには最初にミックスインから、次に `app` から出力された `toVal` と `fromVal` が表示されます。`fromVal` が存在する場合には常にそれが返されるため、最終的には `this.$options.custom` に `hello!` がセットされます。ストラテジを*常に子インスタンスの値を返す*ように変更してみましょう:
Suggested change に沿って修正を行いました。

2020-09-24 15:17 UTC, Nag729 commented
レビューいただいた指摘に対応しました！
ご確認よろしくお願いします🙏

2020-09-24 15:33 UTC, kazupon approved these changes

2020-09-24 15:34 UTC, kazupon commented
確認しました。
LGTMです！
CIでエラーが起きていますが、翻訳作業に支障がない(このPRとは別事象)ので、マージします！

翻訳ありがとうございました！

2020-09-24 15:34 UTC, merged