docs: Essentials > Event Handling の翻訳
vuejs-jp/ja.vuejs.org pull request #87
Opened 2020-09-23 15:06 UTC by entaku0818

## Description of Problem
 Essentials > Event Handling の翻訳
https://v3.vuejs.org/guide/events.html 

## Proposed Solution
https://jp.vuejs.org/v2/guide/events.html
を参考に翻訳

## Additional Information
特になし

2020-09-23 16:02 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
確認お願いします！

2020-09-27 15:02 UTC, entaku0818 commented on src/guide/events.md
> +## イベントの購読
修正します！

2020-09-27 15:08 UTC, entaku0818 commented on src/guide/events.md
> +## イベントの購読
@kazupon 
他の部分も改行あうように修正しました！

2020-09-28 02:03 UTC, kazupon approved these changes

2020-09-28 02:04 UTC, kazupon commented
対応ありがとうございました！
確認しました！
CIでエラーが起きていますが、翻訳作業に支障がない(このPRとは別事象)なので、マージしますね。

翻訳ありがとうございました！

2020-09-28 02:04 UTC, merged