docs: Essentials > Template Syntax の翻訳 (#5)
vuejs-jp/ja.vuejs.org pull request #91
Opened 2020-09-25 17:33 UTC by nalpan

## Description of Problem
https://v3.vuejs.org/guide/template-syntax.html の翻訳
resolve #5 

## Proposed Solution
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/syntax.md
を参考に翻訳

## Additional Information

2020-09-26 15:53 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
翻訳内容については、コメントした細かいもの以外大丈夫です！
対応お願いします。 🙏

2020-09-26 15:53 UTC, kazupon commented on src/guide/template-syntax.md
> +内部では、Vue はテンプレートを Virtual DOM の描画関数にコンパイルします。リアクティブシステムと組み合わせて、Vue は再描画に必要なコンポーネントをインテリジェントに把握でき、アプリケーションの状態が変わった時に最低限の DOM 操作を適用します
- ここの `Virtual DOM` は以下のように、訳してしまった大丈夫です。
- `render functions` は、初見の方が分かるように括弧付きで `render` を入れて置いて欲しいです。

```suggestion
内部では、Vue はテンプレートを仮想 (Virtual) DOM の描画 (render) 関数にコンパイルします。リアクティブシステムと組み合わせて、Vue は再描画に必要なコンポーネントをインテリジェントに把握でき、アプリケーションの状態が変わった時に最低限の DOM 操作を適用します
```

2020-09-26 15:53 UTC, kazupon commented on src/guide/template-syntax.md
> +もし、あなたが Virtual DOM の概要に詳しく、JavaScript で直接描画するのを好む場合、テンプレートの代わりに[直接 render 関数で書く](render-function.html)ことも可能で、オプションで JSX をサポートしています。
ここの Virtual DOM も同じく。
```suggestion
もし、あなたが仮想 DOM の概要に詳しく、JavaScript で直接描画するのを好む場合、テンプレートの代わりに[直接 render 関数で書く](render-function.html)ことも可能で、オプションで JSX をサポートしています。
```

2020-09-26 15:53 UTC, kazupon commented on src/guide/template-syntax.md
> +{{ number + 1 }}
ここは改行されていますが、ドキュメントのメンテナンス上 (diff のコンフリクトを避ける) 原文と同じにしておいてください。 🙏

2020-09-28 14:41 UTC, nalpan reviewed
@kazupon 
squashしてしまいましたが…対応しました、ご確認お願いします🙏

2020-09-28 14:41 UTC, nalpan commented on src/guide/template-syntax.md
> +内部では、Vue はテンプレートを仮想 (Virtual) DOM の描画 (render) 関数にコンパイルします。リアクティブシステムと組み合わせて、Vue は再描画に必要なコンポーネントをインテリジェントに把握でき、アプリケーションの状態が変わった時に最低限の DOM 操作を適用します
https://github.com/vuejs-jp/ja.vuejs.org/pull/91#discussion_r495468517
`Virtual DOM`と`render function`を対応しました！

2020-09-28 14:41 UTC, nalpan commented on src/guide/template-syntax.md
> +もし、あなたが仮想 DOM の概要に詳しく、JavaScript で直接描画するのを好む場合、テンプレートの代わりに[直接 render 関数で書く](render-function.html)ことも可能で、オプションで JSX をサポートしています。
https://github.com/vuejs-jp/ja.vuejs.org/pull/91#discussion_r495468554
こちらも`Virtual DOM`対応しました！

2020-09-28 14:41 UTC, nalpan commented on src/guide/template-syntax.md
>  {{ number + 1 }} {{ ok ? 'YES' : 'NO' }} {{ message.split('').reverse().join('')
https://github.com/vuejs-jp/ja.vuejs.org/pull/91#discussion_r495468747
原文に戻しました！

2020-09-28 14:59 UTC, kazupon approved these changes

2020-09-28 15:00 UTC, kazupon commented
対応ありがとうございます。
確認しました。
LGTMです。

CIでエラーが発生していますが、翻訳作業に支障がない(このPRとは別事象)なので、マージします！

翻訳ありがとうございました！

2020-09-28 15:00 UTC, merged