docs: Essentials > List Rendering の翻訳 #8
vuejs-jp/ja.vuejs.org pull request #92
Opened 2020-09-26 08:23 UTC by utano320

## Description of Problem
https://v3.vuejs.org/guide/list.html の翻訳
resolve #8

## Proposed Solution
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/list.md 
を参考に翻訳

2020-09-26 16:12 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
翻訳ですが、コメントした細かい系以外は、大丈夫です！
レビューコメントの対応お願いします！ 🙏

2020-09-26 16:12 UTC, kazupon commented on src/guide/list.md
> +コンソールを開いて前の `items` 配列の例で変更メソッドを呼び出して遊んでみてください。例えば `example1.items.push({ message: 'Baz' })` のようにしてみましょう。
v2 ベースだと思いますが、play の訳 `遊ぶ` はやっぱり違和感があるので、ここでは意訳で `試す` にしておいてください。 🙏

2020-09-27 00:54 UTC, utano320 commented on src/guide/list.md
> +コンソールを開いて前の `items` 配列の例で変更メソッドを呼び出して遊んでみてください。例えば `example1.items.push({ message: 'Baz' })` のようにしてみましょう。
修正しました！

2020-09-27 00:56 UTC, utano320 commented
@kazupon レビューありがとうございます！修正いたしましたので、ご確認よろしくお願いします！

2020-09-27 12:58 UTC, kazupon approved these changes

2020-09-27 12:58 UTC, kazupon commented
対応ありがとうございました。
確認しました！
CIでエラーが起きていますが、翻訳作業に支障はない(このPRとは別事象)なので、マージします！

翻訳ありがとうございました！

2020-09-27 12:59 UTC, merged