Advanced Guides > Compotion API > Template Refs の翻訳
vuejs-jp/ja.vuejs.org pull request #93
Opened 2020-09-26 08:29 UTC by konu96

## Description of Problem
resolve #36 

https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs の翻訳をした

## Proposed Solution

## Additional Information

2020-09-26 08:31 UTC, konu96 commented on src/guide/composition-api-template-refs.md
> +> この節ではサンプルコードで [単一ファイルコンポーネント](single-file-component.html)の文法を使用しています。
セクションをそのままにしていいか分からなかったので、取り敢えず「節」と訳しています

2020-09-26 16:24 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2020-09-26 16:24 UTC, kazupon commented on src/guide/composition-api-template-refs.md
>  ## Template Refs
Tempalte Refs ですが、 以下のようにテンプレート参照でお願いします！ 🙏
```suggestion
## テンプレート参照
```

2020-09-26 16:24 UTC, kazupon commented on src/guide/composition-api-template-refs.md
> +> このガイドはすでに [Composition API 導入](composition-api-introduction.html) を読んでいることを前提に書かれています。もしまだ読んでいないのなら、先に読みましょう。
Composition API の訳は、`コンポジション API` で訳していくことにしたので、以下のようにしておいてください。 🙏 
```suggestion
> このガイドはすでに [コンポジション API 導入](composition-api-introduction.html) を読んでいることを前提に書かれています。もしまだ読んでいないのなら、先に読みましょう。
```

2020-09-26 16:24 UTC, kazupon commented on src/guide/composition-api-template-refs.md
> +Composition API を使うとき、 [リアクティブ refs](reactivity-fundamentals.html#creating-standalone-reactive-values-as-refs) と [テンプレート refs](component-template-refs.html) のコンセプトは同じになります。
- Composition API の訳は、`コンポジション API`
- reactive refs は `リアクティブ参照`
- template refs は `テンプレート参照`
```suggestion
コンポジション API を使うとき、 [リアクティブ参照](reactivity-fundamentals.html#creating-standalone-reactive-values-as-refs) と [テンプレート参照](component-template-refs.html) のコンセプトは同じになります。
```

2020-09-26 16:24 UTC, kazupon commented on src/guide/composition-api-template-refs.md
> +描画コンテキストに `root` 変数を渡していて、`ref="root"` 経由で div 要素とバインドします. 仮想 DOM のパッチアルゴリズムの中で、 もし VNode の `ref` キーは描画コンテキストの ref に対応すると、VNode の対応する要素またはコンポーネントインスタンスに ref の値が割り当てられます。これは仮想 DOM のマウント/パッチ処理中に実行されるので
`binding` は以下のように `束縛します` お願いします！
```suggestion
描画コンテキストに `root` 変数を渡していて、`ref="root"` 経由で div 要素と束縛します. 仮想 DOM のパッチアルゴリズムの中で、 もし VNode の `ref` キーは描画コンテキストの ref に対応すると、VNode の対応する要素またはコンポーネントインスタンスに ref の値が割り当てられます。これは仮想 DOM のマウント/パッチ処理中に実行されるので、テンプレート refs では初期描画に値だけを取得できます。
```

2020-09-26 16:24 UTC, kazupon commented on src/guide/composition-api-template-refs.md
> +テンプレート refs　は他の refs と似た挙動をします。つまり、リアクティブかつコンポジション関数に渡せる(または返せる)ことができます。
- template refs は `テンプレート参照`
- ここの refs (原文ででてくる用語の refs) は references の略称。なので、訳も参照で。
```suggestion
テンプレート参照は他の参照と似た挙動をします。つまり、リアクティブかつコンポジション関数に渡せる(または返せる)ことができます。
```

2020-09-26 16:24 UTC, kazupon commented on src/guide/composition-api-template-refs.md
> +コンポジション API のテンプレート refs を `v-for` 内部で使う時に特別な処理はされないです。代わりに、関数 refs を使って独自処理を実行してください。
`function refs` は意訳的に以下のようにすると分かりやすいです。
```suggestion
コンポジション API のテンプレート参照を `v-for` 内部で使う時には特別な処理はされないです。代わりに、参照を提供する関数を使って独自処理を実行してください。
```

2020-09-27 11:09 UTC, konu96 commented
細かい点までレビューありがとうございます. 対応したのでお手隙の際に、レビューお願いします.

2020-09-27 12:55 UTC, kazupon commented
対応ありがとうございました。
確認しました！
CIでエラーが起きていますが、翻訳作業に支障はない(このPRとは別事象)なので、マージします！

翻訳ありがとうございました！

2020-09-27 12:55 UTC, kazupon approved these changes

2020-09-27 12:55 UTC, merged