docs: Advanced Guides > Compotion API > Provide / Inject の翻訳
vuejs-jp/ja.vuejs.org pull request #96
Opened 2020-09-28 12:30 UTC by bobstrange

## Description of Problem

resolve #35

[v3.vuejs.org/guide/composition-api-Provide-Inject.html](https://v3.vuejs.org/guide/composition-api-Provide-Inject.html) の翻訳をしました。

用語は [Provide / Inject](https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/component-provide-inject.md) に合わせています。

## Proposed Solution

## Additional Information

2020-09-28 15:10 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
翻訳内容については大丈夫です。
コメントした細々ですが、よろしくお願いします！ 🙏

2020-09-28 15:10 UTC, kazupon commented on src/guide/composition-api-provide-inject.md
> +
ここの改行ですが削除して原文と同じような行構成でお願いします。:pray:
今後のドキュメントのメンテナンス上、なるべく diff によるコンフリクトを避けるためです。

2020-09-28 15:10 UTC, kazupon commented on src/guide/composition-api-provide-inject.md
> +`setup()` 内で `provide` を使う場合、始めに `vue` から明示的に `provide` をインポートします。
ここの改行ですが、前と同じく、削除して原文と同じような行構成でお願いします。🙏

2020-09-28 15:10 UTC, kazupon commented on src/guide/composition-api-provide-inject.md
> +同様に `setup()` 内 `inject` を使う場合も `vue` から明示的に `inject` をインポートする必要があります。
文章構成についても、改行を同じく原文と同じ構成で維持お願いします！ 🙏

2020-09-28 15:10 UTC, kazupon commented on src/guide/composition-api-provide-inject.md
> +2. デフォルト値 (**Optional**)
Optional は以下のように訳せます！
```suggestion
2. デフォルト値 (**任意**)
```

2020-09-29 03:08 UTC, bobstrange commented
@kazupon 
レビューありがとうございます :-)
指摘していただいた箇所について修正しました。
再度ご確認よろしくお願いします :bow:

2020-09-29 14:25 UTC, kazupon approved these changes

2020-09-29 14:26 UTC, kazupon commented
対応ありがとうございました！
確認しました！
LGTMです！ 👍 
CIでエラーが起きていますが、翻訳作業に師匠がない(このPRとは別事象)なので、マージします！

翻訳ありがとうございました！

2020-09-29 14:26 UTC, merged