docs: Essentials > Components Basics の翻訳 #11
vuejs-jp/ja.vuejs.org pull request #98
Opened 2020-09-29 12:09 UTC by kou1127h

## Description of Problem
resolve #11 

## Additional Information
https://jp.vuejs.org/v2/guide/components.html
と重複する内容が多かったので、基本的にはこちらを踏襲しています。

2020-09-29 15:12 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
翻訳内容については、大丈夫そうです。
細かい部分、コメントしましたが、対応お願いします。 🙏

2020-09-29 15:12 UTC, kazupon commented on src/guide/component-basics.md
> +<button>
textlint実行していただいてありがとうございます！
codeのところ、今の設定だと反応してしまうんですね。
なるべく、今後のドキュメントのメンテ上、行構成などあまり構造を変えたくないので、lintで対応したところ、こちら一旦原文と同じく、戻していただけますでしょうか？ :pray:

2020-09-29 15:12 UTC, kazupon commented on src/guide/component-basics.md
> +ここでは単純な例を示していますが, 典型的な Vue アプリケーションでは文字列テンプレートではなく単一ファイルコンポーネントを使用します。 詳しくは[こちら](single-file-component.html)で解説されています。
特にへりくだる必要はないので、ドキュメントの翻訳トーンをこれまで通り合わせたいので、以下の suggestion ようにしてもらえますか？
```suggestion
ここでは単純な例を示していますが, 典型的な Vue アプリケーションでは文字列テンプレートではなく単一ファイルコンポーネントを使用します。 詳しくは[こちら](single-file-component.html)で解説しています。
```

2020-10-01 11:47 UTC, kou1127h commented on src/guide/component-basics.md
> +<button>
お返事遅れてすみません！

> 一旦原文と同じく、戻していただけますでしょうか？

こちらの修正は一度僕の環境で誤ってフォーマットされたものを原文準拠に戻したものになっております。
ので、この辺りに関して修正は不要な認識ですがいかがでしょうか？

2020-10-01 16:07 UTC, kazupon commented
対応ありがとうございました。
CIでエラーが起きていますが、翻訳作業に支障はない(このPRとは別事象)なので、マージしますね！

翻訳ありがとうございました！

2020-10-01 16:07 UTC, merged