docs: Reusability & Composition > Teleport の翻訳
vuejs-jp/ja.vuejs.org pull request #99
Opened 2020-09-29 14:22 UTC by Pittan

## Description of Problem
resolve #27

レビューよろしくおねがいします 🙇

2020-09-29 15:21 UTC, kazupon requested changes
レビュー 👀 しました！
翻訳内容はOKです！
細かいですが、コメント 💬 したところの対応お願いします。 🙏

2020-09-29 15:21 UTC, kazupon commented on src/guide/teleport.md
> +`<teleport>` を使って、Vue にこの HTML を "**body**" タグに "**teleport**" させるよう、`modal-button` を変更しましょう。
英語に疎い人もいるので、以下のように、カタカナ日本語で読み方もいっしょにお願いします！
```suggestion
`<teleport>` を使って、Vue にこの HTML を "**body**" タグに "**teleport (テレポート) **" させるよう、`modal-button` を変更しましょう。 
```

2020-09-29 15:21 UTC, kazupon commented on src/guide/teleport.md
> +この場合、 `child-component` が別の場所にレンダリングされたとしても、`parent-component` の子のままとなるため、`name` prop を受け取ります。
ここの `prop` は以下のようにプロパティでお願いします！
```suggestion
この場合、 `child-component` が別の場所にレンダリングされたとしても、`parent-component` の子のままとなるため、`name` プロパティを受け取ります。
```

2020-09-29 15:35 UTC, Pittan commented
@kazupon san, 
レビューありがとうございます！いただいた指摘の対応 & 1点軽微な修正を入れました 🙏

2020-09-30 04:22 UTC, kazupon approved these changes

2020-09-30 04:23 UTC, kazupon commented
対応ありがとうございます！
確認しました！LGTMです！
CIでエラーが起きていますが、翻訳作業に支障はない(このPRとは別事象)なので、マージします！

翻訳ありがとうございました！

2020-09-30 04:23 UTC, merged